### PR TITLE
Add a sizing doc for KSQL

### PR DESCRIPTION
**Pull request by rodesai**

### CODE REVIEW

**Comment by miguno** [comment]
Agree with @apurvam. We need to include this doc into the TOC of the rest of the KSQL docs.

+1 to include it under the KSQL Operations chapter.

**Comment by rodesai** [comment]
Good call @apurvam. Updating

**Comment by apurvam** [comment]
I don't think you can just change the branch from master to 4.1.0-post trivially. What needs to be done is to create a patch file which just contains your changes, and then create a new branch off of 4.1.0-post, and then apply the patch there. 

You can overwrite the current branch if you like (by doing a local delete and then recreating it from 4.1.0-post and then force pushing to the remote branch) to keep the PR the same.

**Comment by joel-hamill** [comment]
@apurvam @rodesai  i run into this frequently. what i usually do is:

```
1. Copy the commit hash  
2. Run git reset --hard origin/<new-target-branch> 
3. git cherry-pick <original-commit-hash>
4. git push origin -f <your-branch> 
5. Reset the target branch of the PR in browser
```

**Comment by rodesai** [comment]
@joel-hamill  I tried something like that and it didn't go quite right so I closed this and opened https://github.com/confluentinc/ksql/pull/1190

**Pull request closed without merging**
