### PR TITLE
feat: ksql-test-runner tool returns exit code "1" on test failure

### LINKED ISSUE #4665: ksql-test-runner tool should return non-zero code on test failure
Currently `ksql-test-runner` tool returns `0` exit code even if tests fail. It brings some inconvenience running this tool e.g. in CI environment. One has to check the output of `stdout` and `stderr` and manually parse it in order to check if tests were successful, otherwise CI will always treat the test as successful, even if it's not.

**To Reproduce**
Just make the `ksql-test-runner` tool to fail and check the exit code.

*input.json*
```
{
  "inputs": [
    {"topic": "x", "timestamp": 0, "key": null, "value": {"a": 1}}
  ]
}
```

*output.json*
```
{
  "outputs": [
    {"topic": "y", "timestamp": 0, "key": null, "value": {"a": 1}}
  ]
}
```

*statements.sql*
```
CREATE STREAM x(a INT) WITH(KAFKA_TOPIC='x', VALUE_FORMAT='JSON');
```

And run the `ksql-test-runner`:
```
/opt/ksql# ksql-test-runner -s queries.sql -i input.json -o output.json
        >>>>> Test failed: test did not generate any queries.
Expected: is not an empty collection
     but: was <[]>
/opt/ksql# echo $?
0
```

**Expected behavior**
The last command
```
/opt/ksql# echo $?
```
should output a non-zero exit code. It could either always be equal to `1` for any fail, or it may differ depending on failure reason (e.g. invalid input/output definition, invalid assertion, unexpected output, etc.)

### PR DESCRIPTION
**Pull request by grubchr**
### Description 
Fixes #4665 

Current behavior is the ksql-test-runner exits with only a "0" exit code regardless if it encounters an error while executing or if any tests fail that it is running. This prevents use in a CI/CD deployment pipeline. The change I submit here will let ksql-test-runner return exit code "1" if any test failure or errors are encountered and a "0" exit code if all tests completed successfully.

### Testing done 
I have included modifications to existing unit tests that verify the ksql test runner does return a "0" exit code on successful executions and a "1" exit code on any test failures or errors encountered while attempting to run the ksql tests.

unknown

unknown

image

I have also executed the KsqlTestingTool.java class from my IDE with parameters to a ksql test I wrote and validated the program returns the expected result codes for both a successful test and a failed test.

I also ran the unit tests locally before and after my changes.

image

### Reviewer checklist
- [X] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [X] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Review by JimGalasyn — APPROVED** [review]
LGTM, thanks!

**Review by jzaralim — APPROVED** [review]
LGTM. Our CI tool for external users is failing atm so I opened another PR to test your changes with our internal CI. If that passes, then we'll merge this to master.

**Comment by grubchr** [comment]
> LGTM. Our CI tool for external users is failing atm so I opened another PR to test your changes with our internal CI. If that passes, then we'll merge this to master.

Good to know. I had to locally replace some package refs in the pom files to use the latest versions of publicly available packages while I was making this change.

**Comment by jzaralim** [comment]
it passed, merging!

**Comment by grubchr** [comment]
> it passed, merging!

Would you know when this might be included in a release?

**Comment by jzaralim** [comment]
It's hard to pinpoint a timeframe. We have a release planned for early 2023, and this commit will be in the one after that.

**Pull request merged**
