### PR TITLE
fix: Set auto.register.schemas to false by default #8995

### PR DESCRIPTION
**Pull request by bvarghese1**
### Description 
- INSERT statement ends up registering new schemas because ksqldb uses
  auto.register.schemas=true by default
- If user doesn't have WRITE permissions on SR, the INSERT statement fails with
  authorization denied. Users don't really need WRITE permission on SR to insert
  data into a topic.
- When schema_id is used during CREATE, we set auto.register.schemas to false
- Therefore, to keep it consistent this commit sets auto.register.schemas to
  false by default which should prevent registering schemas during INSERT
- Additionally, this is a config which is not exposed to the user

### Testing done 
Updated Unit Tests
QTT - TODO (InProgress)

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by lihaosky** [comment]
Hi @bvarghese1 , currently `insert` registers schema because schema may not exist already in SR. Does this PR change that behavior? There's another PR trying to add `connect.name` when registering schema for insert.

**Comment by bvarghese1** [comment]
> Hi @bvarghese1 , currently `insert` registers schema because schema may not exist already in SR. Does this PR change that behavior? There's another PR trying to add `connect.name` when registering schema for insert.

Doesn't the CREATE statement register a schema with SR? Currently, we are registering a new schema every time an Insert statement is executed. This PR is trying to alter that behavior.

**Comment by bvarghese1** [comment]
> > Hi @bvarghese1 , currently `insert` registers schema because schema may not exist already in SR. Does this PR change that behavior? There's another PR trying to add `connect.name` when registering schema for insert.
> 
> Doesn't the CREATE statement register a schema with SR? Currently, we are registering a new schema every time an Insert statement is executed. This PR is trying to alter that behavior.

I was working on fixing the QTT and now I understand by what you mean `There's another PR trying to add `connect.name` when registering schema for insert.`

**Comment by bvarghese1** [comment]
Closing this PR because we have found out that we cannot set auto.register.schemas to false due to breaking changes.

**Pull request closed without merging**
