### PR TITLE
docs: add version picker

### PR DESCRIPTION
**Pull request by colinhicks**
### Description 
Draft for discussion.

Versions dropdown sits at the right-hand side of the docs nav, on larger screens:
image

And smaller screens:
image

Expanded:
image

Version data pulls from the microsite:
https://ksqldb.io/versions/handleVersions.js

### CODE REVIEW

**Comment by colinhicks** [comment]
We'll want to discuss which branch to target.

**Comment by MichaelDrogalis** [comment]
Nice one @colinhicks

**Comment by colinhicks** [comment]
@JimGalasyn The aim is to get this on all the rendered versions of the docs. I was thinking we would merge to master, then cherry-pick into the version branches. What do you think would be best?

**Comment by JimGalasyn** [comment]
@colinhicks Awesome! Defs merge to master and I'll cherry-pick to the live branch (0.8.1-ksqldb) and maybe one or two earlier branches -- the only ones we have are `0.8.x-ksqldb` `v0.7.0-ksqldb`.

**Pull request merged**
