### PR TITLE
fix: make endpoints available while waiting for precondition

### PR DESCRIPTION
**Pull request by vcrfxia**
### Description 

Same as https://github.com/confluentinc/ksql/pull/5047 (re-opened a new PR because of a GitHub mishap).

### Testing done 

Same.

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by purplefox** [comment]
If it's the same, then why do I need to review it? ;)

**Comment by vcrfxia** [comment]
You don't. I just need to fix the failing test :)

**Comment by vcrfxia** [comment]
But if you like pressing green buttons you're more than welcome to ;D

**Comment by agavra** [comment]
I like pressing green buttons

**Comment by purplefox** [comment]
Go on, you do it then! ;)

**Pull request merged**
