### PR TITLE
fix: parser Removed KEY from nonReserved in SqlBase.g4

### PR DESCRIPTION
**Pull request by sukalpomitra**
### Description 
This fixes https://github.com/confluentinc/ksql/issues/6896. Removed KEY from nonReserved in SqlBase.g4 under ksqldb-parser
pr

### CODE REVIEW

**Comment by sukalpomitra** [comment]
[clabot:check]

**Comment by sukalpomitra** [comment]
Screenshot 2021-03-16 at 12 05 57 AM
hi @mjsax @agavra please help me. The error in jenkins build is nnot reproducible on my branch. How can I fix this test failure?

**Comment by agavra** [comment]
hello @sukalpomitra thanks for the PR! You need to build locally for it to verify, do a `mvn clean install -pl :ksqldb-parser` and you should be able to reproduce the issue. 

Perhaps more importantly, however, this isn't a backwards compatible change (which is why the tests are failing). We'll need to be thoughtful about how we make this change so as not to break existing applications.

**Comment by sukalpomitra** [comment]
hi @agavra - All tests are passing
Screenshot 2021-03-20 at 12 54 34 PM

**Comment by agavra** [comment]
hello @sukalpomitra - tests are not passing in all modules (you can see the Jenkins CI build). I suspect the root cause is because of what I mentioned, that this change is not necessarily backwards compatible.

**Comment by vvcephei** [comment]
Closing stale PR. I'm sorry that we didn't get this done. Please resubmit as a new PR if you still want to get it in.

**Pull request closed without merging**
