### PR TITLE
docs: missing docker exec -it option

### PR DESCRIPTION
**Pull request by thekana**
### Description 
_What behavior do you want to change, why, how does your patch achieve the changes?_

### Testing done 
_Describe the testing strategy. Unit and integration tests are expected for any behavior changes._

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Review by JimGalasyn — APPROVED** [review]
LGTM, thank you for the fix!

**Comment by thekana** [comment]
@JimGalasyn how can I rerun CI?

**Comment by JimGalasyn** [comment]
@thekana, docs aren't built by this Jenkins job. If you merge this PR, I'll cherry-pick it to the live branch and re-publish.

**Comment by JimGalasyn** [comment]
@thekana This fix is live now, thanks again! https://docs.ksqldb.io/en/latest/operate-and-deploy/installation/installing/

**Pull request merged**
