### PR TITLE
add test for SelectValueMapper

### PR DESCRIPTION
**Pull request by dguy**

### CODE REVIEW

**Comment by dguy** [comment]
@hjafarpour @bluemonk3y added a couple of happy path tests for the `SelectValueMapper` we need to think about how we are handling errors here. i.e, if a column doesn't map we just log and record a null. I'm not sure that is correct, but maybe it is ??

**Comment by hjafarpour** [comment]
If we get an exception while computing a column, the whole row should be considered corrupted.
Then we can have two options:
1. Stop the whole query
2. Log the error, ignore the row and keep processing the next rows.
We can have both of these and have user to pick the desired behavior via config. We can have option 1 as the default behavior.

**Comment by bluemonk3y** [comment]
I can see us needing to support both. Ideally loaded via properties set during that user runtime. i.e. run script stuff.sql - and it contains various properties associated with streams etc. Best option for now would be to expose it (similar to streams ex handling).

**Comment by dguy** [comment]
We should file a ticket for handling the error scenarios. It needs some thought

**Comment by dguy** [comment]
https://github.com/confluentinc/ksql/issues/393

**Pull request merged**
