### PR TITLE
Set lag check interval default to 10m

### PR DESCRIPTION
**Pull request by vvcephei**
### Description 
Increase default lag check interval from 5 seconds to 10 minutes.

### Testing done 
Unit/Integration tests run.

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by vvcephei** [comment]
Hey @AlanConfluent ,  @guozhangwang mentioned to me that calls to check the Streams task lags seem to be stacking up. This is not at all a lightweight operation. Although the current _position_ is known locally for each task, the current end offsets for each topic are not known. They're checked via an AdminClient call which itself can take a few seconds to complete.

With this in mind the current default interval is way too frequent.

Another way to fix this is not to broadcast the task lags, but only the task positions. Then, only the query router would need to fetch the end offsets periodically, which would dramatically cut down on broker API calls and also improve the accuracy of lag estimates.

If that latter approach seems more attractive, I'm happy to propose an update to KIP-535 and implement it in Streams and KSQL.

**Comment by vinothchandar** [comment]
>this is not to broadcast the task lags, but only the task positions. 

@vvcephei we have already discussed this at length. We do need some notion of lags, to avoid queries from accessing completely stale information..  i.e just knowing the most caught up replica is not sufficient.. need to also ensure that caught up position is recent enough. 

>>calls to check the Streams task lags seem to be stacking up. This is not at all a lightweight operation.

@guozhangwang where was this ? I am okay with increasing the default. but 10m will make this feature totally unusable. Why can't this operation be performed every 10 seconds say?

**Comment by AlanConfluent** [comment]
@vvcephei 

> With this in mind the current default interval is way too frequent.

Fair enough, though 10m seems rather long.  Is there something a bit more reasonable in between?  After all, after a rolling restart, the new host will effectively be unavailable for this window of time since the lag information will not exist at a routing host and it won't route to a host of unknown lag.

> 
> Another way to fix this is not to broadcast the task lags, but only the task positions. Then, only the query router would need to fetch the end offsets periodically, which would dramatically cut down on broker API calls and also improve the accuracy of lag estimates.

In Ksql's current setup, there's not a fixed router node.  Any node can be a router, and therefore all nodes must have end offset information.  A solution that could work would be a single node is nominated the end offset fetcher in a given cluster, and that node shares the information with every other node, just as it does lags currently.  That way it would be fetched once per cluster and could be done at a higher frequency.  This could potentially be done by the `active` host.

**Comment by vvcephei** [comment]
Hey all,

Yeah, we can totally pick some number between 5 seconds and 10 minutes (there are many to choose from). One thing to note is that having a fixed schedule makes this tradeoff more difficult than it needs to me. For example, nodes would want to broadcast their current lags immediately after rebalances complete, and frequently during initial recovery, but then less frequently during steady state execution. This doesn't mesh very well with the `AbstractScheduledService` model, though.

Regarding the apparently controversial alternative suggestion, if you take a step back, the current situation is that every member of the KSQL cluster will hammer all broker nodes every five seconds to learn the end offsets of every single changelog topic partition in the cluster. They do this regardless of whether any pull request is ever actually executed at all, or if they do, then which stores get queried and how frequently.

Further, by default we're fetching end offsets every five seconds by default so that we can bound the lag of replicas. But the default lag we're bounding by is `Long.MAX_VALUE`. So by default, we don't need to check the lag at all.

My alternative proposal, which admittedly could have been stated more clearly, would be to have the cluster internally broadcast current positions only, and have the query routing logic maintain a loading cache, which it would refresh by querying the end offsets only for the partitions it needs to know, only when its cache has become too stale.

It's also worth noting that we don't need to know the end offset at all if we route to the leader (active task), which is the first node we try on every query.

The point isn't that we have to optimize this in every possible way, but just that it's difficult to consider any optimization as long as broadcasting the end offset is coupled with broadcasting the position.

**Comment by vinothchandar** [comment]
>They do this regardless of whether any pull request is ever actually executed at all, or if they are, then which stores get queried and how frequently.

There are orthogonal optimizations that can be done. So, i ll leave them out of the design discussion. 

>It's also worth noting that we don't need to know the end offset at all if we route to the leader (active task), which is the first node we try on every query.

Not true right.. if the active is restoring, for e.g then we need to know the end offset.. We need to walk all these solutions through different cases before deciding. 

I am open to improving this ofc. but I feel like a GH issue is not the right place to brainstorm this. I find myself retying a bunch of conversations we have already had :) .. Last time, we discussed this, there were two fixes we discussed to eliminate the need for fetching end offsets

1. Have the active alone report endOffset (which it already knows in restoring state or running state as it writes to changelog topic)
2. Kafka Consumer knows its own lag and we were hopeful that we can directly use the endOffset as long as some fetch was going on for that partition.. 

I'd like to exhaust these first.. before we change a lot of design..

**Comment by AlanConfluent** [comment]
I agree that there are a lot of optimizations that can be done, but the couple @vinothchandar listed seem like decent starting points, since they alone would lessen the load quite a bit without hurting accuracy.

It makes sense that adjustable frequency based on state and current pull query load would make for good next steps after those two, if necessary.  (For the sake of HA, we chatted about doing this after a rebalance to make sure there's lag data available).

> As far as this PR goes, we don't have this turned on by default (@AlanConfluent correct me if I am wrong) and 10m is too large.. I'd prefer to just file an issue (which we already have ) for eliminating/making lag fetches safe/realtime and continue there.

Correct, it's not on by default, so this shouldn't be affecting anyone unless they deliberately turn it on, in which case they could also adjust the frequency as well.

**Comment by vvcephei** [comment]
Hey all, I synced with @guozhangwang , and it seems this whole PR was a bit of a misunderstanding. I thought that he was telling me that there was an actual problem with too many end-offset requests to the brokers. By "actual problem", I mean that someone was observing a problem in a real deployment. I.e., I was under the impression that I was handling an escalation. But, in reality, he was just concerned that the current design _might_ cause problems.

I didn't open this PR intentionally to engage in an awkward and unwanted design discussion, just to help resolve a situation that I thought was ongoing and something of which you would already have been aware.

Since it's now clear that there is no such immediate problem, we don't need to continue this discussion at all. Sorry for the waste of time and the out-of-context PR.

**Comment by vinothchandar** [comment]
No problem! @AlanConfluent and I will follow up with discussion on how to improve the freshness of lag fetching, after we do some more research and put together some alternatives..

**Pull request closed without merging**
