### PR TITLE
feat: add test topology rewriter

### PR DESCRIPTION
**Pull request by rodesai**
### Description 

This patch adds a rewriter tool for rewriting test topologies
in the event that the streams topology changes in a backwards
compatible way.

### CODE REVIEW

**Comment by rodesai** [comment]
> What happened to the 'schemas' in the old expected topologies? 

The schemas are still being validated. They are stored in `spec.json`, under "schemas" (e.g. https://github.com/confluentinc/ksql/blob/444fef0d853c347a768c08aff8ce911c9aee4d50/ksql-functional-tests/src/test/resources/historical_plans/average_-_calculate_average_in_select/5.5.0_1576794350087/spec.json#L158).

**Comment by rodesai** [comment]
> Or is this prep work for pushing straight to cloud on each commit?

That's the idea. The current plan is to persist a new spec whenever the execution plan for a given query changes. The current suite contains 2 tests that accomplish this:

* `QueryTranslationTest` iterates over all the persisted specs (under `historical_plans`), builds them, and validates topic data and schemas.
* `PlannedTestsUpToDateTest` ensures that the latest persisted spec for each test case contains a plan that matches the plan that the engine currently builds. If it doesn't, then the test fails. To fix the failure, the developer should (assuming she/he intentionally made a change that would alter the plan) generate a new spec for the test.

This does introduce the possibility that we add specs for unreleased KSQL versions if a given plan changes multiple times between releases. The hope was that this would be relatively infrequent, but maybe that's wishful thinking. For example, if you want to make a common change across the plan incrementally (like adding a field to ExecutionStepProperties) you'll likely hit this (though you could just stage your changes differently).

We could avoid this as you say by only doing this for KSQL bits that we actually release. To do this for releases from master, we need artifacts with concrete versions for code from master (rather than a snapshot). The current plan here is to use the nightly beta releases (e.g. https://github.com/confluentinc/ksql/tree/v5.5.0-beta191204174040). So we would need to, as part of the cloud release process:

- check out the beta tag version and build (or get the release artifact)
- run a spec generator
- commit the generated specs to master.

Ideally the above would be wrapped in a tool, and done automatically. But that's probably a ways off since the whole beta release stuff is still pretty new. So for the time being it's more manual process (more time, more human error, etc) as part of the release.

We could give the current system a go, and re-evaluate if we start creating a lot of plans unnecessarily. WDYT?

**Comment by big-andy-coates** [comment]
> > What happened to the 'schemas' in the old expected topologies?
> 
> The schemas are still being validated. They are stored in `spec.json`, under "schemas" (e.g.
> 
> https://github.com/confluentinc/ksql/blob/444fef0d853c347a768c08aff8ce911c9aee4d50/ksql-functional-tests/src/test/resources/historical_plans/average_-_calculate_average_in_select/5.5.0_1576794350087/spec.json#L158
> 
> ).

Is it though?  Sure, the schema is in the spec. I was aware of this. But that doesn't mean to say there isn't a bug that means its not being manipulated or misused when building the actual serde used for the internal or sink topics.  The old test tracked the schemas used to build the actual serde. I still think this is useful as a sanity check.

**Comment by rodesai** [comment]
> Is it being validated though? Sure, the schema is in the spec. I was aware of this. But that doesn't mean to say there isn't a bug that means its not being manipulated or misused when building the actual serde used for the internal or sink topics. The old test tracked the schemas used to build the actual serde. I still think this is useful as a sanity check.

I haven't changed the mechanism that we use to compute and validate the physical schemas.

When we generate the test spec, we get the physical schemas used to write/read data to/from kafka: https://github.com/confluentinc/ksql/blob/096b78f8648382c4792411bb83914d1e1d7e0c03/ksql-functional-tests/src/test/java/io/confluent/ksql/test/planned/TestCasePlanLoader.java#L166

Then, when the spec is loaded, these schemas go into `TestCase`:
https://github.com/confluentinc/ksql/blob/096b78f8648382c4792411bb83914d1e1d7e0c03/ksql-functional-tests/src/test/java/io/confluent/ksql/test/planned/PlannedTestLoader.java#L80

From there they get verified by the test executor just as they used to.

**Pull request merged**
