### PR TITLE
Harden allowed SELECT syntax

### PR DESCRIPTION
**Pull request by big-andy-coates**
### Description 
Fix for #1425

Harden syntax to:
- _Not_ have optional stream name as the first entry in a select statement.
- _Require_ a `FROM` statement, rather than it being optional, but resulting in NPE if missing.
- _Not_ having supporting multiple sources in the `FROM` statement.

### Testing done 
Manual tested.  

Output from the statement in issue #1425, which is an invalid statement, is now a much more helpful message, rather than an NPE:

```
ksql> select message\
from ratings;
line 1:27: mismatched input ';' expecting {',', 'FROM', 'INTO'}
Caused by: org.antlr.v4.runtime.InputMismatchException
```

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by uurl** [comment]
@big-andy-coates I think the continuation character should work this way not just with the Select statement

**Comment by big-andy-coates** [comment]
@uurl 

> @big-andy-coates I think the continuation character should work this way not just with the Select statement

Sorry, I don't follow. Can you explain what you mean?

The continuation character is working correctly in the issue flagged up in #1425. It is converting:

```
ksql> select message\
from ratings;
```

To the SQL statement `select messagefrom ratings;`. The issue is that this statement results in an NPE, where as it should result in a error message about the statement being malformed.

**Comment by big-andy-coates** [comment]
@uurl,

> @big-andy-coates for example with:
> CREATE STREAM\
> pageviews
> I guess the fix just works for the SELECT statement

So this _should_ be treated by KSQL as the command `CREATE STREAMpageviews`, which _should_ result in a error about not expecting `STREAMpageviews`.  However, I've not tested each and every case at it would take a long time. I guess we could write a test that took a load of valid statements and removed each white space in turn and ensured it threw a parsing exception, rather than any other...

**Comment by hjafarpour** [comment]
@big-andy-coates the issue you referred, #1425 is a CLI issue. We use JLine in our CLI and it supports multiline statement with `\`. When it converts the multi line statement into one line it removed `\` and concats the lines. So if you don't have space in either sides of `\`, the two terms will be concatenated and we will have wrong statement. Regardless we should have a better error message for this. I'll open a PR for it :)

**Comment by big-andy-coates** [comment]
@hjafarpour 

> @big-andy-coates the issue you referred, #1425 is a CLI issue. We use JLine in our CLI and it supports multiline statement with \. When it converts the multi line statement into one line it removed \ and concats the lines. So if you don't have space in either sides of \, the two terms will be concatenated and we will have wrong statement. Regardless we should have a better error message for this. I'll open a PR for it :)

JLine was 'doing the right thing' here. The issue was that KSQL's parser was seeing the following as a valid statement:

```
select messagefrom ratings;
```

The parser was then returning an empty list of queries, resulting in a NPE at some later point.

**Pull request merged**
