### PR TITLE
chore: fix alias resolution in n-way join logic

### PR DESCRIPTION
**Pull request by mjsax**
### Description 
FK-join must resolve table alias correctly.

### Testing done 
_Describe the testing strategy. Unit and integration tests are expected for any behavior changes._

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Review by vcrfxia — COMMENTED** [review]
Thanks @mjsax -- if I'm reading the fix in this PR correctly, this issue impacts not only FK joins but also table-table-table joins where one of the first two tables is aliased. Is that correct? We should add a QTT for this if so. (This would also mean it's a regression for 0.19 if this PR isn't merged before then. Let's make extra sure to not lose track of this.)

Also I renamed the PR title to be a bit more descriptive, and changed the PR type from `fix` to `chore` so that it doesn't show up in the changelog since the fix is only for a unreleased change.

**Review by guozhangwang — APPROVED** [review]
The fix lgtm modulo @vcrfxia 's comments.

**Review by vcrfxia — APPROVED** [review]
Thanks @mjsax -- LGTM, though the PR description could be more informative :)

**Comment by guozhangwang** [comment]
> Thanks @mjsax -- LGTM, though the PR description could be more informative :)

+1 :) I was originally confused by this and https://github.com/confluentinc/ksql/pull/7592 since their titles are the same, now I understand the other is only for table-table-table while this is for fk-table-table.

**Pull request merged**
