### PR TITLE
chore: ksqlDB java client can extend Closeable

### PR DESCRIPTION
**Pull request by wicknicks**
Signed-off-by: Arjun Satish <arjun@confluent.io>

### Description 
ksqldb java client can extend the java.io.closeable interface. 

### Testing done 
clean run of unit tests.

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Review by vcrfxia — COMMENTED** [review]
Thanks @wicknicks . Can we remove the definition of `void close();` in the Client interface, as it's now redundant? LGTM otherwise.

**Comment by wicknicks** [comment]
@vcrfxia the [close() from Closable](https://docs.oracle.com/javase/8/docs/api/java/io/Closeable.html#close--) throws an IOException. I think we want to keep the definition to indicate this method does not throw that exception (will help with backward compatibility).

**Comment by vcrfxia** [comment]
Ah got'cha. This approach sounds good then. Will merge once the PR builder passes.

**Review by vcrfxia — APPROVED** [review]

**Review by guozhangwang — COMMENTED** [review]
LGTM~

**Pull request merged**
