### PR TITLE
MINOR: add ksql-udf-quickstart module to top pom

### PR DESCRIPTION
**Pull request by jarekr**
Need this so we publish this archetype to packages.confluent.io

### CODE REVIEW

**Comment by mitch-seymour** [comment]
Could we wait until https://github.com/confluentinc/ksql/pull/2615 is merged before merging this PR? It contains some small improvements to the artifact we'd be publishing after this PR gets merged.

**Comment by apurvam** [comment]
We should not merge this as the quickstart cannot be built:

```
[INFO] KSQL UDF / UDAF :: Quickstart ...................... FAILURE [  7.477 s]
```

**Comment by mitch-seymour** [comment]
It looks like the issue is with signing the artifact.  I'm not too familiar with the artifact deployment process but made some educated guesses [here](https://github.com/confluentinc/ksql/blob/c2e3a24618a693c21ce2eb8ec04ccf94d183512f/ksql-udf-quickstart/README.md#deploy-artifacts).

There may be additional steps as well. Sorry, I was only to test the artifact signing / deployment locally :( Feel free to bring this in line with any official process for publishing these kinds of artifacts to the Confluent Maven repo. Thanks for your help

**Comment by jarekr** [comment]
superseded by https://github.com/confluentinc/ksql/pull/2616

**Pull request closed without merging**
