### PR TITLE
Fix hash code equals contract

### PR DESCRIPTION
**Pull request by satybald**
Objects which are `.equals()` MUST have the same `.hashCode()`.

### CODE REVIEW

**Comment by satybald** [comment]
@hjafarpour thanks for the review! any chance to look at the PR? It's only one line change ;) cc: @dguy @apurvam @rodesai

**Comment by miguno** [comment]
Is this related to https://github.com/confluentinc/ksql/pull/746?

**Comment by satybald** [comment]
@miguno I don't think so.

**Comment by dguy** [comment]
Thanks @satybald, merged to master

**Pull request merged**
