### PR TITLE
docs: update etc/ksql dir to ksqldb in on-prem topics (DOCS-3685)

### PR DESCRIPTION
**Pull request by JimGalasyn**

### CODE REVIEW

**Comment by JimGalasyn** [comment]
Aw, thanks man!

**Comment by vcrfxia** [comment]
Thanks @JimGalasyn and @agavra ! Looks like the Kafka Tutorials need to be updated too. Is one of you already tracking that?

**Comment by JimGalasyn** [comment]
@vcrfxia I guess not! Which topics do you have in mind?

**Comment by vcrfxia** [comment]
I'm not sure where the source for Kafka Tutorials is located but they should be updated. For example, this one (https://kafka-tutorials.confluent.io/join-a-stream-to-a-table/ksql.html) contains references to `/etc/ksql/`.

**Comment by colinhicks** [comment]
@vcrfxia I'll take care of Kafka Tutorials when we bump the version to 0.8.0 there.

**Pull request merged**
