### PR TITLE
docs: document parallel build

### PR DESCRIPTION
**Pull request by vvcephei**
### Description 

Document how to use parallel build in Maven to speed up tests.

### Testing done 

Ran it locally. Also @agavra has been doing this for a while.

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Review by agavra — APPROVED** [review]
huh wasn't aware that you could pass in a fractional core 😆

**Review by mjsax — APPROVED** [review]

**Comment by mjsax** [comment]
Flaky test failed. Think it's ok to merge without rerunning :)

**Comment by agavra** [comment]
also heads up - semantic pull request requires the first letter after the `:` to be lowercase. I know... it's _very_ pedantic about these things.

**Comment by vvcephei** [comment]
The time for `./mvnw clean verify` dropped from 56 minutes to 45 minutes on my machine with this change.

**Comment by vvcephei** [comment]
Document how to use parallel build in Maven to speed up tests.

Reviewers: Matthias Sax, Almog Gavra

**Pull request merged**
