### PR TITLE
fix: handle leap days correctly during timestamp extraction

### LINKED ISSUE #4864: Correct handling of timestamps belonging to leap days
**Describe the bug**
When ksql encounters a timestamp belonging to a leap day, it currently fails with the following

```
Caused by: java.time.DateTimeException: Invalid date 'DayOfYear 366' as '1970' is not a leap year
at java.time.LocalDate.ofYearDay(LocalDate.java:290)
at java.time.LocalDate.withDayOfYear(LocalDate.java:1118)
at java.time.LocalDate.with(LocalDate.java:1029)
at java.time.LocalDateTime.with(LocalDateTime.java:970)
at java.time.ZonedDateTime.with(ZonedDateTime.java:1311)
at io.confluent.ksql.util.timestamp.StringToTimestampParser.parseZoned(StringToTimestampParser.java:75)
at io.confluent.ksql.util.timestamp.StringToTimestampParser.parse(StringToTimestampParser.java:58)
at io.confluent.ksql.util.timestamp.StringToTimestampParser.parse(StringToTimestampParser.java:48)
at io.confluent.ksql.util.timestamp.StringTimestampExtractor.extract(StringTimestampExtractor.java:45)
at org.apache.kafka.streams.processor.internals.RecordQueue.updateHead(RecordQueue.java:177)
```

**To Reproduce**

Able to reproduce this with a small test case

```
@Test
  public void testEscalation2522() {
    // Given
    final String format = "yyyy-MM-dd'T'HH:mm:ss.SSSX";
    final String timestamp = "2012-12-31T23:59:58.660Z";

    // When
    final long ts = new StringToTimestampParser(format).parse(timestamp);

    // Then

  }
```

**Expected behavior**

Valid epoch timestamp is returned. 

**Actual behaviour**

```
java.time.DateTimeException: Invalid date 'DayOfYear 366' as '1970' is not a leap year

	at java.time.LocalDate.ofYearDay(LocalDate.java:290)
	at java.time.LocalDate.withDayOfYear(LocalDate.java:1118)
	at java.time.LocalDate.with(LocalDate.java:1029)
	at java.time.LocalDateTime.with(LocalDateTime.java:970)
	at java.time.ZonedDateTime.with(ZonedDateTime.java:1311)
	at io.confluent.ksql.util.timestamp.StringToTimestampParser.parseZoned(StringToTimestampParser.java:75)
	at io.confluent.ksql.util.timestamp.StringToTimestampParser.parse(StringToTimestampParser.java:58)
	at io.confluent.ksql.util.timestamp.StringToTimestampParser.parse(StringToTimestampParser.java:48)
	at io.confluent.ksql.util.timestamp.StringToTimestampParserTest.testEscalation2522(StringToTimestampParserTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
```

**Additional context**

### PR DESCRIPTION
**Pull request by vinothchandar**
### Description 
fixes #4864, in a localized way, added a unit test case

### Testing done 
unit tests, also tested using an end-end example with some sample data containing leap days

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by vinothchandar** [comment]
@agavra Would you be able to share your thoughts here..Made a localized fix to get us moving on a production issue.. but there has to be a nicer way to do this prioritization of chrono fields settng order? any other cases that may demand this sort of ordering .. wdyt> ?

**Comment by agavra** [comment]
Honestly I'm not totally sure what the implications of this are. I remember adding significant unit testing around this because the behavior was fragile around partial date formats (see #2499).

If those tests pass, then I don't see harm in having it done the way you suggest here but again anything with datetime parsing in Java is very brittle.

**Comment by vinothchandar** [comment]
@agavra tests seem happy.. We were depending on the ordinal value of these enum and that was making me bit uneasy.  Hopefully, that does not get changed over time.

I confirmed the sorting holds true
Screen Shot 2020-03-24 at 11 05 10 AM
Screen Shot 2020-03-24 at 11 04 52 AM

.
May be a more explicit way is to pick YEAR as the first item and then append the remaining list as is (skipping YEAR)?

**Comment by agavra** [comment]
> May be a more explicit way is to pick YEAR as the first item and then append the remaining list as is (skipping YEAR)?

That might work, but I feel like the most important thing here is to just have a comprehensive suite of tests and then if anything changes from underneath us we'll be able to at least detect and react

**Comment by vinothchandar** [comment]
```
private static final List<ChronoField> CHRONO_FIELDS = Stream.concat(
      Stream.of(ChronoField.YEAR),
      Arrays.stream(ChronoField.values()).filter(f -> !f.equals(ChronoField.YEAR)))
      .collect(Collectors.toList());
```

doing so, fails the tests when `DayOfWeek` is set.

```
java.time.DateTimeException: Invalid date 'DayOfYear 366' as '2011' is not a leap year
```
So there the order is not meaningless. Let me think more.

**Comment by vinothchandar** [comment]
@agavra if you are still curious, the ordering might have some trickiness in general.. 

So I reworked it into a very specific fix: eagerly overriding the year if it's a leap day.

**Pull request merged**
