### PR TITLE
chore: always start queries executed by InteractiveStatementExecutor

### PR DESCRIPTION
**Pull request by stevenpyzhang**
### Description 
Removes the handleRestore() function as it's no longer necessary after the compaction change https://github.com/confluentinc/ksql/pull/5002

Since we remove terminated queries in compaction, we don't need to wait until the restore is complete to start queries.

### Testing done 
Updated unit tests

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by stevenpyzhang** [comment]
> The change LGTM, but I'm a little nervous about test coverage. I couldn't find a test that proved that `start` wasn't called on a terminated query during restore (perhaps it checks to make sure to query with that statement text or something like that is never run). Is there such a test?

@agavra I think the issue here is we're missing test coverage on the `RestoreCommandsCompactor` class, the assumption is that `final List<QueuedCommand> compacted = compactor.apply(restoreCommands);` should remove all these terminated queries so when we're executing, we only execute non-terminated queries.

**Comment by stevenpyzhang** [comment]
Actually now that I think about it, this change might not be necessary, the main thing I was worried about was incompatible commands from a newer version causing the CommandRunner to get stuck on a command during restore, but since we're going to add some form of command versioning and just never execute commands from a newer version, that won't be a concern anymore.

**Comment by agavra** [comment]
thanks for the explanation @stevenpyzhang - I still think this change is worth it with a bit more testing. Reduces the complexity of the code.

**Comment by stevenpyzhang** [comment]
@agavra after digging into this a bit more, I don't think we can do this actually. We still support executing commands without a KsqlPlan in the InteractiveStatementExecutor https://github.com/confluentinc/ksql/blob/master/ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/InteractiveStatementExecutor.java#L317

The compaction logic we have only compacts commands with a KsqlPlan. If there was an old command in the command topic that doesn't have a KsqlPlan, we'd start it even though it could be potentially terminated later with this change.

This should probably be shelved until https://github.com/confluentinc/ksql/pull/4659 is done.

**Pull request closed without merging**
