### PR TITLE
remove jackson dependency in ksql-rest-app.

### PR DESCRIPTION
**Pull request by dguy**
remove jackson dependency in ksql-rest-app as it is pulled in from kafka and the versions clash resulting in failures in the cli when doing `list tables`, `list streams`, `list properties`
remove @JsonUnwrapped from places where it doesn't work

### CODE REVIEW

**Comment by dguy** [comment]
@hjafarpour kafka pulls in jackson 2.9.x and ksql-rest-app was bringing in jackson 2.8.x this means that if you run `bin/ksql-cli local` the `list tables`, `list streams`, `list properties` commands would fail. They didn't fail in the build due to dependency ordering.
It is something to do with the `@JsonUnwrapped` annotation. It seems to work sometimes, but not others.

**Comment by hjafarpour** [comment]
Yes, seems that the problem is because of upgrade to jackson 2.9.x in 4.0.0. I included jackson 2.8.x in the rest app as a temporary fix but we need to look into the REST api along with the entities to make it work with jackson 2.9.x.
Wanna look into it?

**Comment by dguy** [comment]
@hjafarpour i fixed the commands that failed with 2.9.x already. At least the ones I know of.

**Comment by hjafarpour** [comment]
@dguy Great, since this depends on your previous pR, #368 , I will review after we resolve the issues with that PR.

**Comment by dguy** [comment]
retest this please

**Comment by dguy** [comment]
retest this please

**Comment by dguy** [comment]
retest this please

**Pull request merged**
