### PR TITLE
Improve HTTP return code when ksql syntax error occurs

### PR DESCRIPTION
**Pull request by matsumana**
Currently, the HTTP return code is 200 even in case of KSQL syntax error.
but, In this case since it's an input value error, I think that it's better to return 400.

### CODE REVIEW

**Comment by matsumana** [comment]
[clabot:check]

**Comment by apurvam** [comment]
Thanks for the patch @matsumana.. do we know that the CLI handles the error code response correctly? Does it print the error message on the console if it gets a non-200 response? did you test this? If it doesn't work, it would be good to fix that and also add the accompanying tests.

**Comment by matsumana** [comment]
> do we know that the CLI handles the error code response correctly? Does it print the error message on the console if it gets a non-200 response?

In cli, it doesn't check HTTP return code but checks `response.isSuccessful()`.

https://github.com/confluentinc/ksql/blob/045434492346c8f8a02a4d2cdb96e83c3f15873d/ksql-cli/src/main/java/io/confluent/ksql/cli/Cli.java#L344-L346
https://github.com/confluentinc/ksql/blob/045434492346c8f8a02a4d2cdb96e83c3f15873d/ksql-cli/src/main/java/io/confluent/ksql/cli/Cli.java#L350-L351

In rest-app, it always returns `response.isSuccessful()` as `true`.

https://github.com/confluentinc/ksql/blob/0caaaec12f2d411a051a170d7c7decbe329ae3fc/ksql-rest-app/src/main/java/io/confluent/ksql/rest/client/KsqlRestClient.java#L89
https://github.com/confluentinc/ksql/blob/b603d5724417735aceb2e41e80bb9d35d1bf2aac/ksql-rest-app/src/main/java/io/confluent/ksql/rest/client/RestResponse.java#L40-L42
https://github.com/confluentinc/ksql/blob/b603d5724417735aceb2e41e80bb9d35d1bf2aac/ksql-rest-app/src/main/java/io/confluent/ksql/rest/client/RestResponse.java#L96-L98


Actually, I am using this API `/ksql` in [my KSQL WebUI](https://github.com/matsumana/tsujun) and I expect that non-200 will be returned in case of input error.
I think non-200 is good in HTTP API, and actually `/query` returns non-200.

https://github.com/confluentinc/ksql/blob/0caaaec12f2d411a051a170d7c7decbe329ae3fc/ksql-rest-app/src/main/java/io/confluent/ksql/rest/client/KsqlRestClient.java#L114-L118
https://github.com/confluentinc/ksql/blob/2888dba2b511372b4b45add3a54007be0a4e4b01/ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java#L68-L82

**Comment by matsumana** [comment]
> did you test this? If it doesn't work, it would be good to fix that and also add the accompanying tests.

I tested manually so far. I'll add test.

**Pull request closed without merging**
