### PR TITLE
Move key constraints doc to docs-rst

### PR DESCRIPTION
**Pull request by rodesai**

### CODE REVIEW

**Comment by apurvam** [comment]
Are the docs in the right place on 4.1.x?

**Comment by joel-hamill** [comment]
@rodesai i think this doc should be in the /docs folder. ping me if you need help fixing.

**Comment by apurvam** [comment]
@rodesai @joel-hamill yes. all the `.rst` docs should be in `docs-rst` on master. This way we don't have merge issues when merging from 4.1.x to master.

**Comment by joel-hamill** [comment]
@apurvam what's the long-term plan here? so in 4.1.x they are in `/docs`, but on master they're in `/docs-rst`? will `/docs-rst` go away when 4.1.x goes live? i don't really understand how this works.

**Comment by apurvam** [comment]
I think a final step will have to be to delete the `.md` files from master and have a link to the CP docs from Github once the latter are published. Once we delete the `.md` files (and hence the entire docs folder) on master, we can rename the `docs-rst` folder to `docs`.

The problem right now is that we don't have a published version of the `.rst` docs anywhere, so we need to retain the `.md` versions. The `docs-rst` folder allows both to co-exist.

**Pull request closed without merging**
