### PR TITLE
fix: prevent null values in runtimeID cmd records from throwing errors

### PR DESCRIPTION
**Pull request by wcarlson5**
### Description 
It seems that old records have a null value for runtime ID and the deserializer doesn't interrupt that as an empty optional. Se we add a new check to filter those out.

### Testing done 
_Describe the testing strategy. Unit and integration tests are expected for any behavior changes._

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by vpapavas** [comment]
@wcarlson5 Can we add tests for this?

**Comment by wcarlson5** [comment]
There are no tests for loading the backup other than int tests which didn't already catch this. Its a version thing

**Comment by wcarlson5** [comment]
Finished manual testing now restoring and cleaning up incompatible cmds gives us
`Continue [yes or no] (default: no)? yes
Loading backup file ...
1 incompatible command(s) skipped from backup file.
Failed loading backup file.
Error = class org.json.JSONObject$Null cannot be cast to class java.util.Optional (org.json.JSONObject$Null is in unnamed module of loader 'app'; java.util.Optional is in module java.base of loader 'bootstrap')
sh-4.4$ exit

`

**Comment by vpapavas** [comment]
@wcarlson5 That is the same exception I was getting before this change. 
```
Loading backup file ...
1 incompatible command(s) skipped from backup file.
Failed loading backup file.
Error = class org.json.JSONObject$Null cannot be cast to class java.util.Optional (org.json.JSONObject$Null is in unnamed module of loader 'app'; java.util.Optional is in module java.base of loader 'bootstrap')
```
So, it seems the changes in this PR don't address the issue :(

**Comment by stevenpyzhang** [comment]
Can we throw a stack trace so we can see which line exactly it's erroring on?

**Review by vpapavas — APPROVED** [review]
LGTM! Thank you @wcarlson5

**Pull request merged**
