### PR TITLE
fix: typo in TimestampExtractionPolicyFactory

### PR DESCRIPTION
**Pull request by dveeden**
### Description 
Fix typo

### Testing done 
No code changes, just a typo fix

### Reviewer checklist
- [x] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [x] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>") (there are none)

### CODE REVIEW

**Review by nateab — APPROVED** [review]

**Comment by dveeden** [comment]
@nateab Is there anything I can or should do to get this merged?

**Comment by nateab** [comment]
@dveeden ah sorry, they might still have disabled community prs for security reasons (@agavra do you know if thats the case still?)

If that is the issue, I can submit the change from my account and just link to this pr

**Comment by agavra** [comment]
@nateab I'm not sure - I just kicked off another build via a dummy commit, let's see if that helps. If not then we can submit the change from your account and if the build is green just merge this one (we should always give credit to the contributor!)

**Comment by agavra** [comment]
Yeah - looks like it's still the same root cause:
```
ERROR: We have disabled builds for pull requests created by the open source communitydue to build system maintenance.We are working to finish it soon.
```

**Comment by nateab** [comment]
Gotcha thanks for checking, here is the pr to check that the build is green https://github.com/confluentinc/ksql/pull/8578

**Comment by nateab** [comment]
pr is green so gonna merge

**Pull request merged**
