### PR TITLE
docs: update embedded Connect topic for primitive keys (DOCS-3385)

### LINKED ISSUE #4521: Update Embedded Connect Docs for 0.7.0 (Primitive Keys/ENV variables)
https://docs.ksqldb.io/en/latest/tutorials/embedded-connect/ will no longer work after we release 0.7.0 because of the primitive key work. Specifically, we need to specify the `key.converter`:
```sql
CREATE SOURCE CONNECTOR jdbc_source WITH (
  'connector.class'          = 'io.confluent.connect.jdbc.JdbcSourceConnector',
  'connection.url'           = 'jdbc:postgresql://postgres:5432/postgres',
  'connection.user'          = 'postgres',
  'topic.prefix'             = 'jdbc_',
  'table.whitelist'          = 'driver_profiles',
  'mode'                     = 'incrementing',
  'numeric.mapping'          = 'best_fit',
  'incrementing.column.name' = 'driver_id',
  'key'                      = 'driver_id',
  'key.converter'            = 'org.apache.kafka.connect.converters.IntegerConverter');
```

After we do that, we need to also update the create table to indicate that it should create it with an integer key (not string):
```sql
CREATE TABLE driverProfiles (
  rowkey INTEGER KEY,
  driver_id INTEGER,
  make STRING,
  model STRING,
  year INTEGER,
  license_plate STRING,
  rating DOUBLE
)
WITH (kafka_topic='jdbc_driver_profiles', value_format='json', key='driver_id');
```

After this, we need to make sure that all of the JOINs work properly with the key types (either casts, or change the source data).

This work should happen after 0.7.0 is released (and the docker image should reflect that).

----

Lastly, we can update the docker-compose file and remove the third step ("Configure Connect"):
```yml
  ksqldb-server:
    image: confluentinc/ksqldb-server:0.6.0
    hostname: ksqldb-server
    container_name: ksqldb-server
    depends_on:
      - broker
    ports:
      - "8088:8088"
    environment:
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_BOOTSTRAP_SERVERS: broker:9092
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      KSQL_KSQL_CONNECT_WORKER_CONFIG: "/connect/connect.properties"
      KSQL_CONNECT_GROUP_ID: "ksql-connect-cluster"
      KSQL_CONNECT_BOOTSTRAP_SERVERS: "broker:9092"
      KSQL_CONNECT_KEY_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      KSQL_CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      KSQL_CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      KSQL_CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      KSQL_CONNECT_CONFIG_STORAGE_TOPIC: "ksql-connect-configs"
      KSQL_CONNECT_OFFSET_STORAGE_TOPIC: "ksql-connect-offsets"
      KSQL_CONNECT_STATUS_STORAGE_TOPIC: "ksql-connect-statuses"
      KSQL_CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      KSQL_CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      KSQL_CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      KSQL_CONNECT_PLUGIN_PATH: "/usr/share/kafka/plugins"
    volumes:
      - ./confluentinc-kafka-connect-jdbc-5.3.2:/usr/share/kafka/plugins/jdbc
```

### PR DESCRIPTION
**Pull request by JimGalasyn**
Fixes #4521. Example statements still need to be tested. Also fixes a broken link.

### CODE REVIEW

**Comment by agavra** [comment]
Thanks for getting this out @JimGalasyn! I still need to make sure that all of the examples work with the new primitive keys (when testing 0.7.0 we only looked at the first few statements).

**Comment by big-andy-coates** [comment]
Is there any reason this can't be merged? It doesn't seem to change / add any SQL that may be affected by primitive keys... @agavra

**Comment by agavra** [comment]
> Is there any reason this can't be merged? It doesn't seem to change / add any SQL that may be affected by primitive keys... @agavra

It does - we added `rowkey INTEGER KEY` to one of the tables because it wasn't working after primitive keys (type mismatch). I'm worried that future operations down the line might also have type mismatches. see: https://github.com/confluentinc/ksql/pull/4531/files#diff-9681ce0fcdb1bb656cc22f684d8c81a4R245

**Comment by JimGalasyn** [comment]
@agavra @big-andy-coates I merged for the 0.7.0-docs branch that I'm about to make. We can tweak later as necessary.

**Comment by apurvam** [comment]
Looks like this was merged to master, going to close out the related issue #4521

**Pull request merged**
