### PR TITLE
Switch from confluent-log4j to reload4j

### PR DESCRIPTION
**Pull request by xjin-Confluent**
### Description 
_What behavior do you want to change, why, how does your patch achieve the changes?_

### Testing done 
_Describe the testing strategy. Unit and integration tests are expected for any behavior changes._

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Review by agavra — COMMENTED** [review]
thanks @xjin-Confluent - can you also revert https://github.com/confluentinc/ksql/pull/9041 as part of this PR?

**Comment by xjin-Confluent** [comment]
@agavra  Since this PR is on 7.2.x, I will merge and pint it.  Reverting https://github.com/confluentinc/ksql/pull/9041 (on master only) happens here: https://github.com/confluentinc/ksql/pull/9106

**Review by agavra — APPROVED** [review]
ah thanks @xjin-Confluent - I thought we had backported 9041 but perhaps we didn't. Approved!

**Comment by xjin-Confluent** [comment]
https://github.com/confluentinc/ksql/pull/9041 was for master branch and I believe it was cherry-picked (https://github.com/confluentinc/ksql/commit/162b761f29640cac8a29c1cd39b2b0c3d3a89937) to 7.2.x as well since there is no dedicated PR.  Adding a revert commit here and discard https://github.com/confluentinc/ksql/pull/9106
@agavra

**Comment by agavra** [comment]
@xjin-Confluent this PR is failing with:
```
java.lang.NoClassDefFoundError: Could not initialize class org.slf4j.MDC
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1154)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1210)
```
which was the same error that https://github.com/confluentinc/ksql/pull/9041 fixed

**Comment by xjin-Confluent** [comment]
> @xjin-Confluent this PR is failing with:
> 
> ```
> java.lang.NoClassDefFoundError: Could not initialize class org.slf4j.MDC
> 	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1154)
> 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1210)
> ```
> 
> which was the same error that #9041 fixed

I think that specific project pulls a incompatible definition from confluent-log4j-extentions in common. We have not removed the confluent-log4j definition yet. https://github.com/confluentinc/common/pull/451 is expected to resolve this issue. I will update this when I get a green build.

**Comment by xjin-Confluent** [comment]
@agavra 
I think that specific project pulls a incompatible definition from confluent-log4j-extentions in common. We have not removed the confluent-log4j definition yet. https://github.com/confluentinc/common/pull/451 is expected to resolve this issue. I will update this when I get a green build.

**Comment by xjin-Confluent** [comment]
The latest run succeeded with common change. I will merge the change.
@agavra  Can you help pint merge? I got rejected permission:
```
Do you want to merge the commits to all downstream branches? [y/N]: y
Merging 7.2.x into master
Pushing master
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Waiting on code owner review from confluentinc/ksql.
To github.com:confluentinc/ksql
 ! [remote rejected]       master -> master (protected branch hook declined)
error: failed to push some refs to 'github.com:confluentinc/ksql'
Command "git push origin master" returned non-zero exit status 1
Could not merge automatically -- see above for details, so you gotta do it yourself manually.
See sample instructions at https://confluentinc.atlassian.net/wiki/x/AYCsFw#pintmerge-MergeConflict
Error: Merge failed for one or more projects. ['ksql'] See above for details

**Comment by cadonna** [comment]
@xjin-Confluent @agavra I pint merged the commit to master. Thanks for the PR!

**Pull request merged**
