### PR TITLE
fix: SandboxKafkaTopicClient should use default replication factor if applicable

### LINKED ISSUE #4800: REST API - fails if CS + CT combined (Failed to guarantee existence of topic / Replication factor must be larger than 0)
ksqlDB 0.7.1

Docker Compose: 
[docker-compose.txt](https://github.com/confluentinc/ksql/files/4344709/docker-compose.txt)

Bring the stack up

```
docker-compose up -d
```

Prepared statements to run: 

```
➜ cat src/statements.sql
CREATE STREAM clicks (ip VARCHAR, url VARCHAR, timestamp VARCHAR)
WITH (KAFKA_TOPIC='clicks',
      TIMESTAMP='timestamp',
      TIMESTAMP_FORMAT='yyyy-MM-dd''T''HH:mm:ssX',
      PARTITIONS=1,
      VALUE_FORMAT='Avro');

CREATE TABLE IP_SESSIONS AS
SELECT IP,
       TIMESTAMPTOSTRING(WINDOWSTART,'yyyy-MM-dd HH:mm:ss') AS SESSION_START_TS,
       TIMESTAMPTOSTRING(WINDOWEND,'yyyy-MM-dd HH:mm:ss')   AS SESSION_END_TS,
       COUNT(*)                                             AS CLICK_COUNT,
       WINDOWEND - WINDOWSTART                              AS SESSION_LENGTH_MS
  FROM CLICKS
       WINDOW SESSION (5 MINUTES)
GROUP BY IP;

```

🔴 Try to create a stream over the REST API :

```
➜ statements=$(tr '\n' ' ' < src/statements.sql) && \
    echo '{"ksql":"'$statements'", "streamsProperties": {}}' | \
        curl -X "POST" "http://localhost:8088/ksql" \
             -H "Content-Type: application/vnd.ksql.v1+json; charset=utf-8" \
             -d @- | \
        jq

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8007    0  7331  100   676  74050   6828 --:--:-- --:--:-- --:--:-- 80878
{
  "@type": "statement_error",
  "error_code": 50000,
  "message": "Failed to guarantee existence of topic IP_SESSIONS\nCaused by: Replication factor must be larger than 0.",
  "stackTrace": [
    "io.confluent.ksql.services.KafkaTopicClientImpl.createTopic(KafkaTopicClientImpl.java:135)",
    "io.confluent.ksql.services.KafkaTopicClient.validateCreateTopic(KafkaTopicClient.java:53)",
    "io.confluent.ksql.services.SandboxedKafkaTopicClient.createTopic(SandboxedKafkaTopicClient.java:103)",
    "sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
    "sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
    "sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
    "java.lang.reflect.Method.invoke(Method.java:498)",
    "io.confluent.ksql.util.LimitedProxyBuilder.lambda$buildForwader$8(LimitedProxyBuilder.java:234)",
    "io.confluent.ksql.util.LimitedProxyBuilder$SandboxProxy.invoke(LimitedProxyBuilder.java:312)",
    "com.sun.proxy.$Proxy63.createTopic(Unknown Source)",
    "io.confluent.ksql.topic.TopicCreateInjector.createTopic(TopicCreateInjector.java:186)",
    "io.confluent.ksql.topic.TopicCreateInjector.injectForCreateAsSelect(TopicCreateInjector.java:163)",
    "io.confluent.ksql.topic.TopicCreateInjector.inject(TopicCreateInjector.java:85)",
    "io.confluent.ksql.topic.TopicCreateInjector.inject(TopicCreateInjector.java:75)",
    "io.confluent.ksql.statement.InjectorChain.inject(InjectorChain.java:42)",
    "io.confluent.ksql.statement.InjectorChain.inject(InjectorChain.java:42)",
    "io.confluent.ksql.rest.server.validation.RequestValidator.validate(RequestValidator.java:145)",
    "io.confluent.ksql.rest.server.validation.RequestValidator.validate(RequestValidator.java:112)",
    "io.confluent.ksql.rest.server.resources.KsqlResource.handleKsqlStatements(KsqlResource.java:225)",
    "sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
    "sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
    "sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
    "java.lang.reflect.Method.invoke(Method.java:498)",
    …
      ],
  "statementText": "CREATE STREAM clicks (ip VARCHAR, url VARCHAR, timestamp VARCHAR) WITH (KAFKA_TOPIC='clicks',       TIMESTAMP='timestamp',       TIMESTAMP_FORMAT='yyyy-MM-dd''T''HH:mm:ssX',       PARTITIONS=1,       VALUE_FORMAT='Avro');  CREATE TABLE IP_SESSIONS AS SELECT IP,        TIMESTAMPTOSTRING(WINDOWSTART,'yyyy-MM-dd HH:mm:ss') AS SESSION_START_TS,        TIMESTAMPTOSTRING(WINDOWEND,'yyyy-MM-dd HH:mm:ss')   AS SESSION_END_TS,        COUNT(*)                                             AS CLICK_COUNT,        WINDOWEND - WINDOWSTART                              AS SESSION_LENGTH_MS   FROM CLICKS        WINDOW SESSION (5 MINUTES) GROUP BY IP; ",
  "entities": []
```

✅ Bounce the stack (clean start), remove the CT and try again: 

```
➜ cat src/statements.sql
CREATE STREAM clicks (ip VARCHAR, url VARCHAR, timestamp VARCHAR)
WITH (KAFKA_TOPIC='clicks',
      TIMESTAMP='timestamp',
      TIMESTAMP_FORMAT='yyyy-MM-dd''T''HH:mm:ssX',
      PARTITIONS=1,
      VALUE_FORMAT='Avro');

/tmp/session-windows on 🐳 v19.03.8
➜
➜ statements=$(tr '\n' ' ' < src/statements.sql) && \
    echo '{"ksql":"'$statements'", "streamsProperties": {}}' | \
        curl -X "POST" "http://localhost:8088/ksql" \
             -H "Content-Type: application/vnd.ksql.v1+json; charset=utf-8" \
             -d @- | \
        jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   666    0   408  100   258    149     94  0:00:02  0:00:02 --:--:--   244
[
  {
    "@type": "currentStatus",
    "statementText": "CREATE STREAM clicks (ip VARCHAR, url VARCHAR, timestamp VARCHAR) WITH (KAFKA_TOPIC='clicks',       TIMESTAMP='timestamp',       TIMESTAMP_FORMAT='yyyy-MM-dd''T''HH:mm:ssX',       PARTITIONS=1,       VALUE_FORMAT='Avro');",
    "commandId": "stream/`CLICKS`/create",
    "commandStatus": {
      "status": "SUCCESS",
      "message": "Stream created"
    },
    "commandSequenceNumber": 0,
    "warnings": []
  }
]

/tmp/session-windows on 🐳 v19.03.8 took 3s

```

🔴 Bounce the stack (clean start) and revert to CS + CT as before: 

```
➜ cat src/statements.sql
CREATE STREAM clicks (ip VARCHAR, url VARCHAR, timestamp VARCHAR)
WITH (KAFKA_TOPIC='clicks',
      TIMESTAMP='timestamp',
      TIMESTAMP_FORMAT='yyyy-MM-dd''T''HH:mm:ssX',
      PARTITIONS=1,
      VALUE_FORMAT='Avro');

CREATE TABLE IP_SESSIONS AS
SELECT IP,
       TIMESTAMPTOSTRING(WINDOWSTART,'yyyy-MM-dd HH:mm:ss') AS SESSION_START_TS,
       TIMESTAMPTOSTRING(WINDOWEND,'yyyy-MM-dd HH:mm:ss')   AS SESSION_END_TS,
       COUNT(*)                                             AS CLICK_COUNT,
       WINDOWEND - WINDOWSTART                              AS SESSION_LENGTH_MS
  FROM CLICKS
       WINDOW SESSION (5 MINUTES)
GROUP BY IP;

➜ statements=$(tr '\n' ' ' < src/statements.sql) && \
    echo '{"ksql":"'$statements'", "streamsProperties": {}}' | \
        curl -X "POST" "http://localhost:8088/ksql" \
             -H "Content-Type: application/vnd.ksql.v1+json; charset=utf-8" \
             -d @- | \
        jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7646    0  6970  100   676   5827    565  0:00:01  0:00:01 --:--:--  6392
{
  "@type": "statement_error",
  "error_code": 50000,
  "message": "Failed to guarantee existence of topic IP_SESSIONS\nCaused by: Replication factor must be larger than 0.",
  "stackTrace": [
    "io.confluent.ksql.services.KafkaTopicClientImpl.createTopic(KafkaTopicClientImpl.java:135)",
    "io.confluent.ksql.services.KafkaTopicClient.validateCreateTopic(KafkaTopicClient.java:53)",                                                                                                                                                                                               "io.confluent.ksql.services.SandboxedKafkaTopicClient.createTopic(SandboxedKafkaTopicClient.java:103)",                                                                                                                                                                                    "sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
    "sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
    "sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
    "java.lang.reflect.Method.invoke(Method.java:498)",
    "io.confluent.ksql.util.LimitedProxyBuilder.lambda$buildForwader$8(LimitedProxyBuilder.java:234)",
    "io.confluent.ksql.util.LimitedProxyBuilder$SandboxProxy.invoke(LimitedProxyBuilder.java:312)",
    "com.sun.proxy.$Proxy63.createTopic(Unknown Source)",
    "io.confluent.ksql.topic.TopicCreateInjector.createTopic(TopicCreateInjector.java:186)",
    "io.confluent.ksql.topic.TopicCreateInjector.injectForCreateAsSelect(TopicCreateInjector.java:163)",
    "io.confluent.ksql.topic.TopicCreateInjector.inject(TopicCreateInjector.java:85)",
    "io.confluent.ksql.topic.TopicCreateInjector.inject(TopicCreateInjector.java:75)",
    "io.confluent.ksql.statement.InjectorChain.inject(InjectorChain.java:42)",
    "io.confluent.ksql.statement.InjectorChain.inject(InjectorChain.java:42)",
    "io.confluent.ksql.rest.server.validation.RequestValidator.validate(RequestValidator.java:145)",
    "io.confluent.ksql.rest.server.validation.RequestValidator.validate(RequestValidator.java:112)",
    "io.confluent.ksql.rest.server.resources.KsqlResource.handleKsqlStatements(KsqlResource.java:225)",
    "sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
    "sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
    "sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
    "java.lang.reflect.Method.invoke(Method.java:498)",
    "org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)",
    "org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)",
    "org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)",
    "org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)",
    "org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)",
    "org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)",
    "org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)",
    "org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)",
    "org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)",
    "org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)",
    "org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)",
    "org.glassfish.jersey.internal.Errors.process(Errors.java:292)",
    "org.glassfish.jersey.internal.Errors.process(Errors.java:274)",
    "org.glassfish.jersey.internal.Errors.process(Errors.java:244)",
    "org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)",
    "org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)",
    "org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:679)",
    "org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392)",
    "org.glassfish.jersey.servlet.ServletContainer.serviceImpl(ServletContainer.java:385)",
    "org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:560)",
    "org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:501)",
    "org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:438)",
    "org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)",
    "org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)",
    "org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)",
    "org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581)",
    "org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)",
    "org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1307)",
    "org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)",
    "org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482)",
    "org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)",
    "org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)",
    "org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204)",
    "org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)",
    "org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)",
    "org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)",
    "org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)",
    "org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)",
    "org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:772)",
    "org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)",
    "org.eclipse.jetty.server.Server.handle(Server.java:494)",
    "org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)",
    "org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)",
    "org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)",
    "org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)",
    "org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)",
    "org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)",
    "org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)",
    "java.lang.Thread.run(Thread.java:748)"
  ],
  "statementText": "CREATE STREAM clicks (ip VARCHAR, url VARCHAR, timestamp VARCHAR) WITH (KAFKA_TOPIC='clicks',       TIMESTAMP='timestamp',       TIMESTAMP_FORMAT='yyyy-MM-dd''T''HH:mm:ssX',       PARTITIONS=1,       VALUE_FORMAT='Avro');  CREATE TABLE IP_SESSIONS AS SELECT IP,        TIMESTAMPTOSTRING(WINDOWSTART,'yyyy-MM-dd HH:mm:ss') AS SESSION_START_TS,        TIMESTAMPTOSTRING(WINDOWEND,'yyyy-MM-dd HH:mm:ss')   AS SESSION_END_TS,        COUNT(*)                                             AS CLICK_COUNT,        WINDOWEND - WINDOWSTART                              AS SESSION_LENGTH_MS   FROM CLICKS        WINDOW SESSION (5 MINUTES) GROUP BY IP; ",
  "entities": []
}
```

### PR DESCRIPTION
**Pull request by mjsax**
If replication factor `-1` is used (implying to use the broker default) the
SandboxKafkaTopicClient created a mocked topic with replication factor 0
instead of using the broker default.

If multiple statement are submitted as once (ie, via a file), later
statement could inherit the incorrect replication factor and thus fail,
which fails all statements in the file.

Closes #4800

### CODE REVIEW

**Comment by mjsax** [comment]
This fix should be included in `0.24.0` and `7.1.x`. I opened the PR against `master` as it seems `7.1.x` branch is broker atm. We would need to cherry-pick this this into `7.1.x`.

**Review by vcrfxia — APPROVED** [review]
Thanks @mjsax -- LGTM!

**Comment by swist** [comment]
@mjsax Build is red :( can you double check? Once it's in, can you ping me and I'll cherry pick stuff to `7.1.x`

**Comment by mjsax** [comment]
This PR broke 3 tests.

It's a little tricky to fix: For a proper fix, we need a change in AK. I opened a PR for the AK change, but it will take some time to get it merged: https://github.com/apache/kafka/pull/11648 (could not find a good workaround within ksqlDB code base).

As an intermediate solution, we could disable the three failing test? Thoughts?

**Comment by vcrfxia** [comment]
Hey @mjsax how come it's only the INSERT INTO tests in RecoveryTest that are failing? I'm fine with the overall approach of disabling the tests until the fix propagates, as long as we don't lose track of the ticket to reenable them, but I'm curious why it's only these tests that need the fix and not others.

**Comment by mjsax** [comment]
Thanks for asking. I never thought about it.

Looking into more, the reason is that those tests use non-existing topic `B`. I updated the PR to re-create topic `B` which fixes the tests.

**Comment by mjsax** [comment]
Merged to `master` and (blind) cherry-picked to `7.1.x` (as `7.1.x` is broken atm).

**Pull request merged**
