### PR TITLE
chore: fix CliTest.testDisableVariableSubstitution()

### PR DESCRIPTION
**Pull request by spena**
### Description 
_What behavior do you want to change, why, how does your patch achieve the changes?_

### Testing done 
_Describe the testing strategy. Unit and integration tests are expected for any behavior changes._

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Review by agavra — COMMENTED** [review]
huh, was this a change in AK that we recently picked up? I'm wondering when it happened

**Review by agavra — APPROVED** [review]

**Comment by agavra** [comment]
merging to unblock other PRs - but still want the question answered! 😉

**Comment by spena** [comment]
It changed, on both AK and CCS.

In CP 6.1, the error returned was an unknown partition:
https://github.com/confluentinc/kafka/blob/6.1.0-post/core/src/main/scala/kafka/server/KafkaApis.scala#L1182
```
if (isInternal(topic)) {
          val topicMetadata = createInternalTopic(topic)
          if (topicMetadata.errorCode == Errors.COORDINATOR_NOT_AVAILABLE.code)
            metadataResponseTopic(Errors.INVALID_REPLICATION_FACTOR, topic, true, util.Collections.emptyList())
          else
            topicMetadata
        } else if (allowAutoTopicCreation && config.autoCreateTopicsEnable) {
          createTopic(topic, config.numPartitions, config.defaultReplicationFactor)
        } else {
          metadataResponseTopic(Errors.UNKNOWN_TOPIC_OR_PARTITION, topic, false, util.Collections.emptyList())
        }
```

In CP master, the error returned depends on the topic name. In the case of CLITest, the topic name is invalid, so the `validate` throws an exception and returns a different error:
https://github.com/confluentinc/kafka/blob/master/core/src/main/scala/kafka/server/KafkaApis.scala#L1100
```
nonExistingTopics.map { topic =>
          val error = try {
            Topic.validate(topic)
            Errors.UNKNOWN_TOPIC_OR_PARTITION
          } catch {
            case _: InvalidTopicException =>
              Errors.INVALID_TOPIC_EXCEPTION
          }
```

```
INVALID_TOPIC_EXCEPTION(17, "The request attempted to perform an operation on an invalid topic.",
```

**Comment by agavra** [comment]
Thanks @spena for digging into that!

**Pull request merged**
