### PR TITLE
New UDF for epoch time conversion to different time zones

### PR DESCRIPTION
**Pull request by k1th**
New UDF for epoch time conversion to different time zones to enable windowing by non UTC aligned days.

### Description 
One new UDF class 
io.confluent.ksql.function.udf.datetime.EpochTimeManipulator

### Testing done 
Unit test in io.confluent.ksql.function.udf.datetime.EpochTimeManipulatorTest

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by agavra** [comment]
Thanks for the pull request @k1th! In the upcoming release (0.15) we're planning on adding a `DATETIME` type to ksql (see #5299 and #4148) - it might make sense to hold off on this PR in order to align with the more standard sql syntax for timestamp time zone conversion: https://docs.oracle.com/cd/B19306_01/server.102/b14225/ch4datetime.htm#i1007699 and https://docs.microsoft.com/en-us/sql/t-sql/queries/at-time-zone-transact-sql?view=sql-server-ver15

```sql
-- example taken from SQL server docs
SELECT CONVERT(DATETIME2(0), '2015-03-29T01:01:00', 126)     
AT TIME ZONE 'Central European Standard Time';  
```

In the meantime, if you need this to unblock some product development, you can always roll this as a custom UDF! Let me know if I'm not understanding the functionality of this UDF correctly.

**Comment by k1th** [comment]
We are already using this in our deployments as custom UDF, so we are not really waiting for the PR. 

Regarding the why:
KSQL window operations are aligned to the epoch which is always in UTC. This means it’s impossible to create windows in other timezones.
Because we need windows in Berlin time, we have to modify the rowtime to be a „corrected“ epoch that is offset by the timezone difference at the rowtime point in time. 
The UDF does this in a daylight saving safe way. 
Introducing the DATETIME type won‘t change the window alignment issue.

**Comment by agavra** [comment]
I'm not sure I understand why having the `DATETIME` format along side `AT TIME ZONE` is any different than this UDF? They both allow us to convert one timestamp to another in a different time zone (daylight savings aware)

**Comment by k1th** [comment]
Will KSQL windowing then align to UTC (which is probably the format the datetime will be stored in) or will it align to the time in the selected timezone?

**Comment by agavra** [comment]
The process would be the same as you have with the UDF - you would need to create the new timestamps "corrected" under epoch time and window using those. So it still windows based on UTC time (but if I understand correctly, that's the case with the UDF as well).

**Comment by k1th** [comment]
It would, depending very much on the implementation of rowtime as `DATETIME` with TZs.

- `ROWTIME` implemented as as timestamp with usual DB like semantics: Internally this would be stored as UTC and only upon query be transformed in the user‘s selected TZ. This would need additional syntax for the `WINDOW` clause to allow for selection of TZ as well. 
- `ROWTIME` implemented as a timestamp already converted with the TZ offset. This would do what we want, but not be very DB like. When, as a user, choosing to use another TZ this would mean changing the underlying data by copying into another topic, probably. 

For me, the former would be a better choice when introduced a new `DATETIME` type, but would require the change to the `WINDOW` clause...

**Comment by k1th** [comment]
KSQL 0.18 just came out providing similar functionality, although with the added step of converting to `TIMESTAMP` and back to `BIGINT` like this:

```
SELECT
      TRACKING_DATA[1]->EVENT->TS `event_tsstr`,
      PARSE_TIMESTAMP(TRACKING_DATA[1]->EVENT->TS, 'yyyy-MM-dd''T''HH:mm:ss.SSSX') `event_time`,
      CONVERT_TZ(PARSE_TIMESTAMP(TRACKING_DATA[1]->EVENT->TS, 'yyyy-MM-dd''T''HH:mm:ss.SSSX'), 'UTC', 'Europe/Berlin') `ts_with_offset`,
      UNIX_TIMESTAMP(CONVERT_TZ(PARSE_TIMESTAMP(TRACKING_DATA[1]->EVENT->TS, 'yyyy-MM-dd''T''HH:mm:ss.SSSX'), 'UTC', 'Europe/Berlin')) `epoch_with_offset`,
      TRACKING_DATA[1]->IDENTIFIERS[1]->ID `usage_id`
    FROM MY_EVENTS emit changes limit 1;
```

Do you think we should discard the PR in favor of that?

**Comment by k1th** [comment]
closing because this can be done with built-in methods in 0.18

**Pull request closed without merging**
