### PR TITLE
Add ratings example

### PR DESCRIPTION
**Pull request by blueedgenick**
commiting the 'Ratings' example dataset used for workshop content so we don't lose it

### CODE REVIEW

**Comment by apurvam** [comment]
@blueedgenick can we target this on master?

**Comment by blueedgenick** [comment]
i did think of that initially, but we are already delivering these
trainings on the 0.2/4.0.x code - i.e. the latest released version - so had
thought it better to keep this in-line (we'll likely have to make another
bunch of changes and/or new demos and examples for the next release). happy
to be persuaded otherwise ?

**Comment by apurvam** [comment]
I guess this can be considered a documentation change, so doing it on a release branch is OK. In general, we'd prefer to have only bugfix code changes on the release branch. 

I think this looks good.

**Comment by miguno** [comment]
@apurvam : Can this be merged?

**Comment by apurvam** [comment]
Sure. I thought @blueedgenick was going to do it.

**Comment by miguno** [comment]
@apurvam Not sure he has merge permissions here.  Also, he might not know how to do the `pint` magic. ;-)

**Pull request merged**
