### PR TITLE
revert: consistency APIs (#8947) 

### PR DESCRIPTION
**Pull request by vvcephei**
Reverts the public APIs for monotonic session consistency.

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by vvcephei** [comment]
It looks like the CI build is not set up to use the stabilization repo. I'm running the tests locally before merging.

**Review by agavra — APPROVED** [review]
rubber stamping based on description. LMK if you need any eyes on something specific

**Comment by vvcephei** [comment]
Hey @vpapavas , I'm not removing all of the implementation, just rolling back the public APIs for now. With the public APIs gone, most of the tests don't work anymore, so we have to remove them as well.

**Comment by vvcephei** [comment]
Ok, I gave up. The tests were failing for me locally, but I'm pretty sure it wasn't the fault of this commit. The Jenkins PR builder couldn't run CIT because this branch uses a different repo (the release stabilization repo).

If we face the same test failures in the next RC build, I'll chase it down from there.

**Pull request merged**
