### PR TITLE
chore: ignore new findbugs 4.7.0 detectors causing ksql build to fail

### PR DESCRIPTION
**Pull request by spena**
### Description 
_What behavior do you want to change, why, how does your patch achieve the changes?_
There's an issue with the recent Findbugs 4.7.0 version that introduce new detectors.
https://github.com/spotbugs/spotbugs/issues/2040

The issue seems to fail only on Java 11. This PR excludes the new detectors from findbugs.

### Testing done 
_Describe the testing strategy. Unit and integration tests are expected for any behavior changes._

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Review by mjsax — APPROVED** [review]

**Comment by pgaref** [comment]
We will just need to revert those changes in the next spotbugs release that turns off the false positive alters

**Comment by spena** [comment]
Doing good @big-andy-coates. How about you? Working now in findbugs or what :P? I saw your comments in a findbugs issue and PR which I hoped it would've be ready soon, but I had to patch ksql 'cause it was blocking us. I'll remove these exclusions once there's a findbugs release.

**Comment by xli1996** [comment]
I updated the common to use 4.7.1 which should include @big-andy-coates 's fix. https://github.com/confluentinc/common/pull/466

**Comment by pgaref** [comment]
Hey @xli1996 -- assuming that spotbug version/plugin is inherited from common we should just bump and revert the exclusions introduced here right?

**Comment by pgaref** [comment]
> yes

Awesome @xli1996  -- would you like to do a followup on this?

**Pull request merged**
