### PR TITLE
chore: Sync apache.httpcomponents.version

### PR DESCRIPTION
**Pull request by xjin-Confluent**
### Description 
No behavior changes. This is to upgrade one dependency version to get rid of CVE.
Ref SEC-1974

### Testing done 
Rely on existing tests.

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Review by spena — APPROVED** [review]
LGTM

**Comment by xjin-Confluent** [comment]
Can anyone with permission help with `pint merge` as well? Thanks. This will only need to go into 5.5.x.

**Comment by vcrfxia** [comment]
> Can anyone with permission help with pint merge as well? Thanks. This will only need to go into 5.5.x.

Sure, let me do this now.

**Comment by vcrfxia** [comment]
@xjin-Confluent is there a reason you only want this change on 5.5.x and not 6.0.x? I see it's not applicable for branches beyond 6.0.x but it looks like it should apply to 6.0.x as well.

**Comment by xjin-Confluent** [comment]
6.0.x is already fixed and 6.1.x and later use a different version. This is to pint the commit but the change itself should be applicable to 5.5.x only.

**Pull request merged**
