### PR TITLE
docs: intent for KLIP-39: prepared statements for java client

### PR DESCRIPTION
**Pull request by hpgrahsl**

### CODE REVIEW

**Review by vcrfxia — APPROVED** [review]
Cool! Looking forward to the KLIP :)

**Comment by hpgrahsl** [comment]
@vcrfxia just out of interest. why was there a re-numbering for this KLIP intent to 40, while at the same time, remove the original and already merged number 39?

**Comment by vcrfxia** [comment]
> why was there a re-numbering for this KLIP intent to 40, while at the same time, remove the original and already merged number 39?

I'm not sure. @spena can you comment? Looks like it was part of this change: https://github.com/confluentinc/ksql/pull/6259/files#diff-752e0a532035b9ba84628bf90c45d09501ed8432c7ff7218c99a37adb9924d9cL83

**Comment by spena** [comment]
Mmm, I don't know what I did there. Sorry for that. I'll fix the README and change this klip back to KLIP-39. We'll have the available KLIP-40 now. Somebody else can use it in the future.

**Pull request merged**
