### PR TITLE
docs: stop recommending headless mode

### PR DESCRIPTION
**Pull request by MichaelDrogalis**
### Description 

We're trying to consolidate headless and interactive mode. For a while, we've started to recommend switching to interactive mode to take advantage of pull queries. We should make this our official recommendation to stop contradicting ourselves in the docs.

### CODE REVIEW

**Comment by MichaelDrogalis** [comment]
@big-andy-coates We made the decision a while ago to move away from headless mode. We should improve interactive mode's ability to restrict adding/removing queries in the future, but we need to stop recommending headless mode in the meantime because it's incongruent with everything else that we're doing.

**Comment by MichaelDrogalis** [comment]
@JimGalasyn Yep, let's make it live for 0.8

**Comment by vcrfxia** [comment]
@big-andy-coates didn't mean to stifle conversation on this issue with my approval, just wanted to unblock merging since the matter is the source of multiple questions a week and we've already been advocating against headless mode in the community slack so we're just playing catch up with our docs here. Please continue the conversation :)

**Comment by JimGalasyn** [comment]
@MichaelDrogalis kk it's live now.

**Pull request merged**
