### PR TITLE
feat: uses internal topics prefix for shared runtimes

### PR DESCRIPTION
**Pull request by wcarlson5**
Without shared runtimes: `_confluent-ksql-default_query_CSAS_CART_EVENT_PRODUCT_1-Join-repartition`
shared runtimes without change: `_confluent-ksql-default_query_-1-CSAS_CART_EVENT_PRODUCT_1-Join-repartition`
shared runtimes with change: `_confluent-ksql-default_query-CSAS_CART_EVENT_PRODUCT_1-Join-repartition`

Will remove the runtime Id from internal topics so that we will be able to use topic in a different application with later work

### Testing done 
_Describe the testing strategy. Unit and integration tests are expected for any behavior changes._

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Review by ableegoldman — APPROVED** [review]
LGTTM!

**Comment by guozhangwang** [comment]
@wcarlson5 should we change the logic in `KafkaTopicClientImpl` too, where `applicationId` is used as the default prefix?

**Comment by wcarlson5** [comment]
@guozhangwang do you mean when deleting internal topics?

**Comment by guozhangwang** [comment]
> I think we do need to but it might require a bit more thought because we will need to change how that is done

Yes I was thinking about the purging of internal topics upon terminating the query indeed. Please let me know what procedure changes we'd need to consider.

**Comment by wcarlson5** [comment]
@guozhangwang  Sophie reminded me I already made that change. I just need to adapt the new thing to use the new prefix instead of the application like you mentioned. I am going to leave `KafkaTopicClientImpl's logic` the same just call it with the prefix instead of app ID

**Comment by guozhangwang** [comment]
Okay, thanks!

**Comment by wcarlson5** [comment]
This caused an issue for running old queries on the same server as queries in the new runtime. The fix can be found here https://github.com/confluentinc/ksql/pull/9470

**Pull request merged**
