### PR TITLE
chore: fix checkstyle errors

### PR DESCRIPTION
**Pull request by mjsax**
### Description 
Seem the upstream checkstyle rules got changed, breaking the build. Even if this is an older branch, to avoid noise about failing builds, it better to just fix. (Not sure if other branches are affected, too, so we could maybe cherry-pick if necessary).

### Testing done 
n/a

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Review by wcarlson5 — APPROVED** [review]
👍

**Comment by mjsax** [comment]
Build failed. Seems we did not cherry-pick https://github.com/confluentinc/ksql/commit/4946003c0cd94c3b18efca513e024b40a58ced1b#diff-f3c19b5a882a0892664b6886c1c392c701264b104c19f52986a1549a476b7389 to 0.20.x branch yet... Updated this PR to get the cherry-pick, too.

**Comment by mjsax** [comment]
Needed to cherry-pick another fix: https://github.com/confluentinc/ksql/commit/71c5833866b09e4b3017d6eda7dfd5c4754c92aa

**Comment by mjsax** [comment]
This is for an older branch. Not important any longer. Closing.

**Pull request closed without merging**
