### PR TITLE
Remove NodeLocation from Node and all places where it is not used.

### PR DESCRIPTION
**Pull request by dguy**

### CODE REVIEW

**Comment by apurvam** [comment]
@hjafarpour, how do we plan on using `NodeLocation` for error messages? If it is something we are planning on doing in the near future, and if the plan makes sense, I would be inclined not to remove them myself.

**Comment by hjafarpour** [comment]
@apurvam we can and should indeed use it now. Any error/exception related to AST nodes in the analyzer and group by analyzer should include the location of the node in the query text. For instance, consider line 386-387 in `Analyzer.java`. We can enhance the error message as follow:

`throw new IllegalArgumentException(
            selectItem.getLocation().get() + "Unsupported SelectItem type: " + selectItem.getClass().getName());`

This will help the user to find the error easily especially when we have a query file or use `Run script` command with a query file.

**Comment by dguy** [comment]
I'll close this PR, however, we shouldn't have unused code lying around in the codebase. Use it or lose it, it adds to the cognitive load of trying to understand what is going on. So, i'd suggest if you are going to indeed use `NodeLocation`, then do it.

**Comment by apurvam** [comment]
I agree with @dguy that we should not introduce code which isn't used as far as possible. This generally leads to suboptimal interfaces.

@hjafarpour can you create an issue to document the work needed to use `NodeLocation` for error messages?

**Pull request closed without merging**
