### PR TITLE
MINOR: remove prompt sign to make copying commands easier

### PR DESCRIPTION
**Pull request by mjsax**

### CODE REVIEW

**Comment by mjsax** [comment]
Let me know if you don't like this change.

**Comment by bluemonk3y** [comment]
From a convention perspective I would prefer to leave as is.

**Comment by mjsax** [comment]
Will leave this open until Michael can review/comment. I found it annoying to copy command to command line as I need to make sure to not include the prompt character.

**Comment by miguno** [comment]
I share the same opinion as @bluemonk3y.  I'd leave it as-is @mjsax.  (If we learn that many users have the same problem we can reconsider.)

**Comment by mjsax** [comment]
Ok. Closing this PR.

**Pull request closed without merging**
