### PR TITLE
fix: update client to fix build

### PR DESCRIPTION
**Pull request by wcarlson5**
### Description 
update default schema registry client to include new methods

### Testing done 
_Describe the testing strategy. Unit and integration tests are expected for any behavior changes._

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by lihaosky** [comment]
QQ: is this trying to fix `SandboxedSchemaRegistryClientTest$UnsupportedMethods.shouldThrowOnUnsupportedOperation` failure? If so, seems it's still failing.

**Comment by wcarlson5** [comment]
Yes, I needed to update the test still. should  be fixed now

**Comment by wcarlson5** [comment]
This also needs to get picked to 7.0.x

**Review by lihaosky — APPROVED** [review]
lgtm!

**Comment by lihaosky** [comment]
Can you update the description as well? Thanks!

**Pull request merged**
