### PR TITLE
Schema inference for tables

### PR DESCRIPTION
**Pull request by hjafarpour**
This PR fixes issue with case sensitivity of inferred field names in avro tables.

### CODE REVIEW

**Comment by apurvam** [comment]
We should add a test for schema inference for tables created from an Avro topic at the very minimum

**Comment by miguno** [comment]
This PR is meant to fix https://github.com/confluentinc/ksql/issues/557.

**Comment by miguno** [comment]
Also, can we please double-check that this PR (the code) matches what we have documented as the expected state in `docs/`, e.g. `examples.md` and `syntax-reference.md`?

For example, I am expecting that you can now do a CT like:

```sql
CREATE STREAM pageviews
  WITH (KAFKA_TOPIC='pageviews-avro-topic',
        KEY='pageid',
        VALUE_FORMAT='AVRO');
```

I'd also suggest to add an actual CREATE TABLE example to the existing CREATE STREAM example at https://github.com/confluentinc/ksql/blob/master/docs/examples.md#avro-format-and-integration-with-confluent-schema-registry.

**Comment by hjafarpour** [comment]
@apurvam the `AvroUtilTest` tests this issue but for end to end test I will have to make changes in `KsqlResourceTest` which needs changes that may affect other parts of the code/Tests accidentally. Improving tests for RestAPI package will be one of the enhancements we will do after this PR.
@miguno I updated the examples page and added a sample for `CREATE TABLE` with inference for avro.

**Comment by apurvam** [comment]
We don't have to add an integration test. I am not sure why we can't use the right mocks to test precisely what schema is computed and stored for a given `CREATE TABLE`, `CREATE STREAM` statement.

**Comment by apurvam** [comment]
Also, how does this case sensitivity issue cause schema inference to be broken exactly? That is something worth putting in the description of the PR.

Without tests and without the description, we have to take it on faith that this actually fixes anything.

**Comment by apurvam** [comment]
Avro fields are case sensitive? Does that mean that a single schema can have two top level fields named `fooBar` and `foobar`?

**Comment by apurvam** [comment]
Apparently, Avro fields are case sensitive: https://avro.apache.org/docs/current/spec.html

So doesn't that mean that our Avro support has the problem where we would clobber fields with the same name but different case?

**Pull request merged**
