### PR TITLE
fix: untracked file after cloning on Windows

### LINKED ISSUE #4023: Untracked file after cloning
After forking and cloning the repo (following the CONTIBUTING doc) on `Windows`, the status of the local repo is the follwong one:

```
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        ksql-functional-tests/src/test/resources/expected_topology/0_6_0-pre/sink-partitions-replicas_-_Use_the_legacy_default_sink_properties_for_the_sink_topic_if_default_partitions_and_replicas_were_set

nothing added to commit but untracked files present (use "git add" to track)
```
It seems that is due to unicode chars in the filename.

I added `git config core.precomposeunicode false`, but it seems it doesn't resolve the issue: the status is the same.

Any hint?

```
$ git --version
git version 2.24.0.windows.2
```

### PR DESCRIPTION
**Pull request by albertosantini**
### Description 
This patch resolves a problem on Windows.
After cloning the repo, git status shows one untracked file.

This is a due to the trailing period in the file name.

Fix #4023.

See also the the comments in the old PR https://github.com/confluentinc/ksql/pull/4046.

### Testing done 
I added and commit again the file.
Then I cloned again the repo and now it is ok.

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [X] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by albertosantini** [comment]
@big-andy-coates I am sorry for the partial PR.

My main point of pain (on Windows) is that file doesn't have any trailing period.
I verified with git bash and with cmd shell. 

```
...
-rw-r--r-- 1 alberto.santini 1049089 2375 Dec 12 09:27  sink-partitions-replicas_-_Use_the_legacy_default_sink_properties_for_the_sink_topic_if_default_partitions_and_replicas_were_set
...
```
Basically I see that file as untracked.

Indeed I was wondering if I need to do some changes (renaming, for instance) to the actual file (that with the period); in this case I cannot do anything, because my git state is not coherent just after cloning.

Shall you help me, please?

About testing. 
Fixing this on Windows it is only the first step, before building and testing as suggested in CONTRIBUTING doc. Indeed I have other problems for building and testing. See https://github.com/confluentinc/ksql/issues/4084.

**Comment by albertosantini** [comment]
I recovered a Linux box and I achieved to rename the expected topology file, removing the trailing period.

**Comment by big-andy-coates** [comment]
> I recovered a Linux box and I achieved to rename the expected topology file, removing the trailing period.

Ah yes, of course you're going to have issues renaming a file you can't get on your filesystem. My bad!

Thanks for sorting. You're contribution is much appreciated!

**Comment by albertosantini** [comment]
Tested. Forked and cloned again.

```
$ git clone git@github.com:albertosantini/ksql.git
Cloning into 'ksql'...
remote: Enumerating objects: 35, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 132597 (delta 9), reused 13 (delta 4), pack-reused 132562
Receiving objects: 100% (132597/132597), 38.44 MiB | 9.75 MiB/s, done.
Resolving deltas: 100% (69696/69696), done.
Updating files: 100% (2705/2705), done.
22:29:58 [/c/woot/var/my]
$ cd ksql
22:30:05 (master u=) [/c/woot/var/my/ksql]
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
$ git log --oneline
04de30e74 (HEAD -> master, origin/master, origin/HEAD) fix: untracked file after cloning on Windows (#4122)
d5974e1c4 chore: fix join left right names (#4136)
4a6141a9d docs: add functions index to markdown docs (DOCS-3049) (#4135)
...

$ git --version
git version 2.24.1.windows.2
```

Perfect!

**Pull request merged**
