### PR TITLE
docs: intent for klip-44: ksqlDB Go client

### PR DESCRIPTION
**Pull request by VanceLongwill**

### CODE REVIEW

**Comment by rmoff** [comment]
For consideration, https://github.com/rmoff/ksqldb-go/ does exist. However, I am new to Go and it was just an experiment in learning and probably won't pass muster :)

Once this KLIP is implemented I will happily add a note to my repo that it is deprecated in favour of a proper replacement.

**Comment by VanceLongwill** [comment]
[clabot:check]

**Review by spena — APPROVED** [review]
lgtm

**Comment by spena** [comment]
Thanks @VanceLongwill for the proposal. I'm looking forward to see this client implemented.

**Pull request merged**
