### PR TITLE
docs: propose KLIP-14

### PR DESCRIPTION
**Pull request by big-andy-coates**
### Description 

Proposal for switching `ROWTIME` to be a pseudo -column.  Read the proposal [here](https://github.com/confluentinc/ksql/blob/013a31707005a7e00338e25fd0ed3037426babe8/design-proposals/klip-14-rowtime-as-pseudocolumn.md)

### CODE REVIEW

**Comment by agavra** [comment]
#3734 - linking for reference

**Comment by MichaelDrogalis** [comment]
LGTM, thanks for the ping

**Comment by big-andy-coates** [comment]
> LGTM @big-andy-coates. Out of curiosity, how will psuedocolumn values be stored/serialized?

If/when the user includes `ROWTIME` in the projection, it will be included in the schema. This includes the schema of data stored in any state store.}

In practical terms, this means that any query not referencing rowtime will not include rowtime in the data stored into the state store. Where as any query making use of rowtime will include that as a value column within the statestoes schema,

**Comment by big-andy-coates** [comment]
looks like there is general agreement with what is being proposed in this minor KLIP, hence merging.

**Pull request merged**
