### PR TITLE
test: add ImmutabilityTest to api module

### PR DESCRIPTION
**Pull request by big-andy-coates**
### Description 

Adds a copy of the `ImmutabilityTest` to the new leaf `ksql-api` module to ensure types in this class are checked for valid `@Immutability` annotations.

### Testing done 

Manually locally.  Test fails.  Raising PR to highlight issues.

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by big-andy-coates** [comment]
The new test fails because the following classes are marked as `Immutable` but, potentially, aren't:

io.confluent.ksql.api.server.protocol.QueryResponseMetadata
io.confluent.ksql.api.server.protocol.QueryStreamArgs
io.confluent.ksql.api.server.protocol.InsertsStreamArgs

@purplefox would you mind taking a look and fixing these classes, please?

**Comment by purplefox** [comment]
I think this is out of date wrt to my latest changes, but will take a look.

**Comment by purplefox** [comment]
I took a look at this.
The test fails on 3 classes:
* InsertsStreamArgs - the map being passed into the constructor is not copied. That is true, but it's only called when deserializing from the wire, and the original map is not used by the caller after that, so it's not an issue. I could fix this by copying but I don't want to as a) it's not necessary and b) this is protocol code - we have to be very careful about making unnecessary copies for performance reasons.
* QueryResponseMetaData - the lists being passed in are not copied. Again, true but they're also not passed around elsewhere by the caller, and again this is protocol code.
* QueryStreamArgs - same as InsertStreamArgs.

I think we should remove the Immutable annotation from these classes. I will follow up with another PR to do this.

**Comment by purplefox** [comment]
https://github.com/confluentinc/ksql/pull/4591

**Comment by big-andy-coates** [comment]
Handled by https://github.com/confluentinc/ksql/pull/4591

**Pull request closed without merging**
