### PR TITLE
Add bootstrap server option to sample

### PR DESCRIPTION
**Pull request by SoyeeDst**
In my initial play, the console was stuck after entering the command `ksql-cli local` without any extra information provided. Eventually realized that the bootstrap-server can be updated by going through the code.

### CODE REVIEW

**Comment by miguno** [comment]
@SoyeeDst: Thanks for your PR!

We already document this functionality here:
https://github.com/confluentinc/ksql/blob/0.1.x/docs/concepts.md#standalone-mode

Your PR suggests that we also add this to the non-Docker quickstart.  So let me ask:  The quickstart assumes that everything is run locally with default settings, hence there's no need to change the `bootstrap.servers` config.  For which reason did you need to change this config?  Were you stuck walking through the quickstart guide, or do you suggest that the quickstart guide should also be a place where we should mention that you can customize the `bootstrap.servers` setting?

**Comment by SoyeeDst** [comment]
@miguno 

Probably I and my team mates got wrong documents, and didn't reach the link you mentioned above.

We were just complete beginners to run this fantastic tool to get some insight, so followed the quickstart documentation step by step but still3virtual box installed previously. And then, run the ksql local but found that the screen was like stuck and didn't render any output.

My team mates ran into the same issue that motivated me to go into the code, that made me realized that this option enabled me to specify the bootstrap servers. It worked fine after directing this to my virtual box then.  From my view of point, I think it would be better to mention this explicitly here to give the beginners a successful walk through.

**Comment by miguno** [comment]
Thanks @SoyeeDst for this information.

> We were just complete beginners to run this fantastic tool to get some insight, so followed the quickstart documentation step by step but still3virtual box installed previously. And then, run the ksql local but found that the screen was like stuck and didn't render any output.

Can you clarify what the problem was, and why changing the `bootstrap.servers` setting (I assume you needed to change it from the default of `localhost:9092` to something different?) was the solution to the problem?  I am asking because it sounds to me as if your actual problem was something different, e.g. perhaps we need to make the quickstart instructions more clear to ensure that no prior Kafka processes are running from earlier experiments of the user?

**Comment by SoyeeDst** [comment]
Sorry for the above typos,  I have corrected it. 

Generally speaking, I have a virtual box locally containing Confluent platform 3.3.0 which can be accessible via the private IP address, in my case, it is 192.168.33.10. Hence the connection information for Kafka brokers should be "192.168.33.10:9092"

In your code, https://github.com/confluentinc/ksql/blob/master/ksql-cli/src/main/java/io/confluent/ksql/cli/commands/Local.java, the default bootstrap server is hard-coded to "localhost:9092" if no such option is specified. My problem disappeared after overriding this option to my personal address "192.168.33.10:9092", that's why I think this quickstart should contain this to give the beginner a signal that the option can be customized.

**Comment by miguno** [comment]
@SoyeeDst: Ah, I think I understand now.

Let me know if the following summary is correct:  You didn't follow the exact instructions of the quickstart, but instead wanted to re-use an existing Confluent Platform installation that was already running in a VirtualBox VM of yours.  And the Kafka broker running inside this existing VM was listening on and accessible via `192.168.33.10:9092`?

**Comment by bluemonk3y** [comment]
running cli as follows should help: bin/ksql-cli local --properties-file=config/ksqlserver.properties

**Comment by SoyeeDst** [comment]
@miguno to the point, thanks @miguno @bluemonk3y

**Pull request closed without merging**
