### PR TITLE
add-some-unit-tests

### PR DESCRIPTION
**Pull request by TheRealHaui**
Added some unit tests.

### CODE REVIEW

**Comment by TheRealHaui** [comment]
[clabot:check]

**Comment by hjafarpour** [comment]
@TheRealHaui Thanks for your contribution. You need to sign Contributor License Agreement before merging your PRs.

**Comment by TheRealHaui** [comment]
[clabot:check]

**Comment by TheRealHaui** [comment]
@hjafarpour
Your contribution license was signed by me.

**Comment by hjafarpour** [comment]
@TheRealHaui We made some refactoring in the code. Would you please update your code accordingly before we can merge it. 
Thanks.

**Comment by miguno** [comment]
@hjafarpour : If @TheRealHaui doesn't have the time to follow-up, I'd suggest that we help to update the code in this PR to match latest `master`.

**Comment by TheRealHaui** [comment]
I am going to update the code in the next few days.
Haven't had time yet.

**Comment by TheRealHaui** [comment]
Thanks for the kind proposal.

**Comment by miguno** [comment]
@TheRealHaui:
> I am going to update the code in the next few days. Haven't had time yet.

Great, that's even better. :-)

Thank you!

**Comment by TheRealHaui** [comment]
@hjafarpour, @miguno 
Here we go.

**Comment by TheRealHaui** [comment]
Updated branch to current code.
Tests work locally without problems.
Can't see why codacy reports problems.
Probably a problem of codacy.

**Comment by bluemonk3y** [comment]
@TheRealHaui  - you can ignore codacy...

**Comment by bluemonk3y** [comment]
@TheRealHaui  - sorry - but we are working on the 4.0.x branch. Its to do with some upcoming work. Would you be able to switch it over?

**Comment by TheRealHaui** [comment]
Something went completely wrong during switching to 4.0.x branch ...
Going to correct issues in the next few days.

**Comment by TheRealHaui** [comment]
@hjafarpour 
Now everything should work.

**Comment by dguy** [comment]
retest this please

**Comment by TheRealHaui** [comment]
@dguy 
Thank you for your answer.

Unfortunately I can't build anything using the 4.0.x branch!
I guess it is necessary to change something in the .m2/settings.xml file because utilizing "mvn clean install -U -X" gives me this exeception: Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project io.confluent.ksql:ksql-parent:pom:4.0.0-SNAPSHOT: Could not find artifact io.confluent:common-utils:jar:4.0.0-SNAPSHOT in confluent (http://packages.confluent.io/maven/)

**Comment by TheRealHaui** [comment]
Any advice?

**Comment by dguy** [comment]
@TheRealHaui you could try adding:
```
<mirror>
     <id>confluent-nexus-central</id>
     <mirrorOf>default,central,confluent</mirrorOf>
     <url>https://nexus.confluent.io/repository/maven-public</url>
   </mirror>
 </mirrors>
```

**Comment by TheRealHaui** [comment]
@dguy
Thanks for your advice.
Tried it but it doesn't help.
However, asked the question regarding building in the Slack chat: https://confluentcommunity.slack.com/archives/C6UJNMY67/p1509368674000098

Thanks for merging.

**Pull request merged**
