### PR TITLE
feat: support for NOT NULL

### PR DESCRIPTION
**Pull request by fjbecerra**
### Description 
Ticket [4436](https://github.com/confluentinc/ksql/issues/4436)

It supports `not null` for all ksql data types, including complex ones like `Struct` ,` Maps`, `Arrays`. It also supports defining `not null` in nested fields.

**Keywords:**

- `not null` for required field/s
- `null` or blank (as current ksql version) for optinal field/s. 

###Testing done:
I’ve included unit test and functional tests

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by agavra** [comment]
thanks for the pull request @fjbecerra! 

This is a feature that we're actively working on (we're at the active discussion phase right now) but I'm afraid the scope spans beyond what is implemented in this PR and it requires some additional design discussions (KLIP). If you're looking for some good places to contribute, I can point you to some other starter tickets - otherwise, we'll make sure to loop you in when we've started feature development!

**Comment by fjbecerra** [comment]
hey @agavra, 
ok, np. Yup, point me some starter tickets, please!

**Comment by agavra** [comment]
hey @fjbecerra these three tickets look promising:

- https://github.com/confluentinc/ksql/issues/5852
- https://github.com/confluentinc/ksql/issues/6652
- (maybe) https://github.com/confluentinc/ksql/issues/4239

We have some meatier issues out there as well, but I think these three should be pretty contained (they're ordered by what I think is difficulty)

**Comment by vvcephei** [comment]
Closing stale PR. I'm sorry that we didn't get this done. Please resubmit as a new PR if you still want to get it in.

**Pull request closed without merging**
