### PR TITLE
refactor: renamed method to avoid checkstyle error

### PR DESCRIPTION
**Pull request by purplefox**
### Description 

Rename a method that triggers a checkstyle error.

### Testing done 

N/A

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by vcrfxia** [comment]
Did we change checkstyle configurations recently? This method appears to have been introduced two months ago, and checkstyle errors fail our builds.

(Also changed the PR title from "fix" to "refactor" as "fix" is for bugfixes and appear in the auto-generated changelog while other types of commits such as "refactor" and "style" do not. Perhaps the label for this change should be "style" rather than "refactor" -- I don't feel strongly.)

**Comment by purplefox** [comment]
> Did we change checkstyle configurations recently? This method appears to have been introduced two months ago, and checkstyle errors fail our builds.
> 
> (Also changed the PR title from "fix" to "refactor" as "fix" is for bugfixes and appear in the auto-generated changelog while other types of commits such as "refactor" and "style" do not. Perhaps the label for this change should be "style" rather than "refactor" -- I don't feel strongly.)

I'm not sure if there were changes recently, but I always notice this error if I run checks on all files in the repository, and it's been annoying me ;)

**Comment by purplefox** [comment]
I'm really confused about how the checkstyle maven config works. According to https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/custom-checker-config.html the default settings is sun_checks.xml if none is specified, and we don't seem to specify any in the config. However if I explicit configure it to use sun_checks.xml I get different checking behaviour. Go figure! ;)

**Comment by agavra** [comment]
@purplefox - I think we inherit the checkstyle from a parent pom (look at `common-parent.pom`). Im trying to track down exactly where the resource is.

**Pull request merged**
