### PR TITLE
Fixing typo in ksql timestamp format config key.

### PR DESCRIPTION
**Pull request by jthompson6**
5.0.x version of #1389

### CODE REVIEW

**Comment by apurvam** [comment]
Thanks for the patch @jthompson6 , it looks like there is a test failure:

```
[ERROR] /home/****/workspace/onfluentinc-pr_ksql_PR-1411-5OUKAP5WMID7FKNPOF2SRUZOEXWMMC4OWICLV7PS3KA2KWAEQMQQ/ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java:[137,79] incompatible types: int cannot be converted to java.lang.Long
```

**Comment by apurvam** [comment]
Though I am not sure why this change would cause a test failure. Can you rebase onto the latest version of 5.0.x and we can run the PR builder again.

**Comment by jthompson6** [comment]
Looks like it was fixed in https://github.com/confluentinc/ksql/commit/5249c70bca9ddd266092944c2f5a2a2a56c26c05#diff-7848c43dbebc7bc8c45c12b2c1e2689cR37

**Comment by apurvam** [comment]
Thanks @jthompson6 !

**Pull request closed without merging**
