### PR TITLE
refactor: Rename the implicitFields in the LogicalSchema to metaFields (MINOR)

### PR DESCRIPTION
**Pull request by big-andy-coates**
### Description 

Requested by @agavra 

The naming was causing confusion when compared to the old concept of implicit fields, which included both ROWTIME and ROWKEY. Meta fields only contain ROWTIME at this point, (but may include others in the future, e.g. headers....

### Testing done 

mvn test

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by agavra** [comment]
Please note that this should be titled `refactor: rename implicit... (MINOR)` to follow conventional commits

**Comment by big-andy-coates** [comment]
@agavra 
> Please note that this should be titled refactor: rename implicit... (MINOR) to follow conventional commits

Where's this from? Not come across this before...

**Comment by agavra** [comment]
> Where's this from? Not come across this before...

cc @vcrfxia @MichaelDrogalis - we are trying to generate better changelogs automatically, and we believe that following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/) will help with that. It's enforced via the Semantic Pull Request plugin.

**Comment by big-andy-coates** [comment]
Cool. I know we'd talked about this, but didn't realise we'd actually done something about it ;)

**Pull request merged**
