### PR TITLE
Failing integration tests to highlight issues with identifiers.

### PR DESCRIPTION
**Pull request by big-andy-coates**
This is a potential fixed for #1213.

This issue is that a statement such as

```SELECT foo AS `group` FROM bar;```

fails for Json data, (and probably Avro, though I didn't test explicitly), because the identifier text for the column comes through as `group`. Non-aliases column names, or those aliases without using quotes, always come through as UPPERCASE, and the `KsqlJsonDeserializer` and `KsqlGenericRowAvroDeserializer` rely on this.  When the select has aliases in other cases it can't find them in the schema. (This is mainly due to poor handling of case within the deserializers).

There isn't any docs around how aliasing works, (#1212), so it was unclear if quoting should maintain case or not.  Using backquotes allows users to access data in columns with names that are reserved keywords, (e.g. GROUP),  but only work if the alias is in upper case.

So... I saw two ways of fixing this:

1. Fix the deserializers to be truly case insensitive.
1. Fix the quoted aliasing to always be upper case.

I've gone with option 2, as I figured there may be other parts of the code that also expect uppercase column names. However, I'm happy to switch to option 1 if, for example, quoted names are intended to allow users to set the case of the output schema.  Just let me know!

### CODE REVIEW

**Comment by hjafarpour** [comment]
@big-andy-coates I would suggest to not allow quoted variable names and aliases at the moment and require the names to follow the valid names in avro.
For source messages with unacceptable field names we can provide a mapping in the CREATE statement that would be passed to the deserializer and would create columns with appropriate names. For sink stream/table we can require compatible naming with avro since user will be able to use correct alias.

I would suggest something like this for the source with unsupported field name:

`CREATE STREAM foo (col1 BIGINT, col2 VARCHAR, col3 VARCHAR ) WITH (...., COL_NAME_MAP[('group', 'col1'), ('from', 'col3')]);`

This will indicate that the field with name `group` will be read into the column with name `col1` and the field with name `from` will be read into column with name `col3`.

What do you think?

**Comment by big-andy-coates** [comment]
@hjafarpour 

>  I would suggest to not allow quoted variable names and aliases at the moment

I've not added support for aliases - they were already there.  All I've done is fix the way the case is handled in them. THB, now that I've worked through the solution I actually think option 1 is probably the way to go, i.e. fix the deserializers to truly be case insensitive.

Can't say I'm a fan of the `COL_NAME_MAP` solution. Aliases are a known SQL concept, so are more intuitive / more expected behaviour.

**Comment by hjafarpour** [comment]
Totally agree on the aliases and I should have provided more details. Indeed I didn't suggest to eliminate the aliases. We would still have aliases but I would suggest to impose the limitation so that the aliases conform to the naming in avro (which we can use as one of KSQL naming requirements too).
The map structure I suggested is only a solution for the input data where we don't have control on the field name but we want to use them.
Consider the following example. Elastic creates a column named `@timestamp` in it's output data. If we want to use this column we need to use an acceptable name instead of `@timestamp` so we can use the following:

`CREATE STREAM foo (col1 BIGINT, col2 VARCHAR, col3 VARCHAR ) WITH (...., COL_NAME_MAP[('@timestamp', 'col1'), ('from', 'col3')]);`

Here we tell KSQL that use `col1` instead of `@timestamp` for the column name. This will be done in deserializer only and in the schema of the stream we will have `col1` as column name and won't have `@timestamp`. When deserializer reads the message from the topic, it will use the value of `@timestamp` field in the message as value for `col1` field in the GenericRow.
This way we would make sure that we can read any input field regardless of the field naming by the outside systems.

**Comment by miguno** [comment]
I, too, don't like the `COL_NAME_MAP()` suggestion.

**Comment by big-andy-coates** [comment]
Hi @hjafarpour / @miguno 

I agree we should have a way to _import_ data that contains problematic field names. However, I think the solution you're talking about needs more discussion, and is outside the scope of this PR.

This PR is trying to address issues with the current aliasing and quoting of column names. From what I see, there are three areas where this come into play:

* **Importing**: i.e. CT/CS statements, e.g. ```CREATE STREAM foo (Col1 bigint, "Col2" bigint, `Col3` bigint) WITH (...)```;

* **transforming**: e.g. ```CREATE STREAM foo AS SELECT u AS Col1, v AS "Col2", w AS `Col3`, x, "y", `z`  FROM ...```

* **exporting**:  e.g. ```SELECT u AS Col1, v AS "Col2", w AS `Col3`, x, "y", `z` FROM ...```

In all three cases straight, quoted and back-quoted aliases and column names are already supported, but the quoted and back-quoted don't work as expected.   

Where quoted and back-quoted column names are used, the case of the column name is preserved and used in the schema of the resulting dataset. This definitely happens for Json, and I _think_ Avro, (I'll test this).  Unfortunately, where column names and aliases are not all uppercase, things stop working as expected. Statements still complete and _appear_ to work, but we start getting `null`s in outputs.

This is what I'm trying to address in this PR.

Having now thought about this more, it seems to me, that quoting a column name should preserve the case in the resulting schema, (as downstream systems may care about the case). So I think I've answered my own question, and what I'll do is fix the deserializers to be truly case insensitive.

**Comment by big-andy-coates** [comment]
@miguno  / @hjafarpour, 

So I've had a poke around and can confirm that the current implementation has some nasty edge cases around the handling of case:  Aliases should allow:

1. control the case of the output schema of a query. This works, the output schema does indeed have the correct case.
1. columns whose names are keywords to be used. This works, but the alias must be uppercase, otherwise `null`s are imported. This means you can't use keyword column names _and_ control the output case.
1. multiple columns within a Json message that differ only in case, (Json _is_ case-sensitive, so this is a valid request). This does not work. Only aliases in upper-case will have non-null values, and they will pick up the first field in the schema with the same case-insensitive field name, i.e. potentially the wrong value.

I've added an integration test to cover these called `IdentifiersIntegrationTest`. 

This main issue is that the Json deserializer does not have a way of knowing if an identifier was quoted or not. So it has no way of distinguishing `COL_NAME` from `"COL_NAME"`. The former should do a case-insensitive match, the latter a case-sensitive.

The serializer can be fixed if it can distinguish quoted from non-quoted identifiers. To do this, the schema passed to the deserializer must store this info. Currently, schemas are passed around using Connect's `Schema` type, which has no explicit way of storing this information. 

Possible solutions:

1. don't strip the quotes from field names when building the `Schema` passed to the deserializer. Pro: smallish change now. Con: very easy to miss something and break untested functionality. Future parts of the system need to handle the embedded quotes.
1. pass around the schema using a KSQL specific implementation, rather than Connect's, so we can store this additional information. Pro: makes it easier to extend in the future. Con: wide ranging change.

I can write up a one pager for this.

**Comment by dtheodor** [comment]
The suggestion to be able to "fix" column names at the source works for data ingestion. This doesn't help with the field names of the query's output topic, which will be consumed by applications outside of kafka, I have no way for my target topic to conform to a given schema, instead I have to force all consuming applications to conform to KSQL naming limitations.

I don't understand why you want to keep these naming limitations around. Why would the rules for column names (including valid characters and case sensitivity) be constrained by the internal implementation's (java variables) variable name limitations or by constraints of *one* (avro) out of dozens of serialization formats that may not even be used at all. Please consider getting rid of this technical debt.

**Pull request closed without merging**
