### PR TITLE
Bring version checker improvements to 5.1.x

### PR DESCRIPTION
**Pull request by hjafarpour**
### Description 
This PR brings the version checker improvement to 5.1.x. The improvements were initially merged into master but we want to include it in 5.1 release.
The original PR that was merged into master is #2020 .

### Testing done 
_Describe the testing strategy. Unit and integration tests are expected for any behavior changes._

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by apurvam** [comment]
Thanks @hjafarpour.. Was this tested with the server to make sure that things continue to work?

**Comment by hjafarpour** [comment]
@apurvam I tested it manually with the `phone-home` and it works fine. The data is received correctly. How to handle it will need some minor change in backend.

**Comment by apurvam** [comment]
Why are there two commits? this should just cherry pick from master on to 5.1 and have exactly one commit.

**Comment by hjafarpour** [comment]
The other PR had 27 commits so it was easier to just apply the changes directly. Also there are conflicting changes in master that are not in 5.1 which version checker relied on.

**Pull request merged**
