### PR TITLE
KSE-1845: unpin classgraph dependency to use the version defined in common  (CP-7-7-0-cp1)

### PR DESCRIPTION
**Pull request by janjwerner-confluent**
### Description 
Unpin version of classgraph dependency to use the version defined in common

### Testing done 
_Describe the testing strategy. Unit and integration tests are expected for any behavior changes._

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")
- [ ] Do these changes have compatibility implications for rollback? If so, ensure that the ksql [command version](https://github.com/confluentinc/ksql/blob/master/ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/Command.java#L41) is bumped.

### CODE REVIEW

**Comment by kagarwal06** [comment]
Thanks @janjwerner-confluent for the PR.

The PR build is failing with the following error:
```
[ERROR]   The project io.confluent.ksql:ksqldb-engine:7.7.0 (/home/semaphore/ksql/ksqldb-engine/pom.xml) has 1 error02:18
[ERROR]   'dependencies.dependency.version' for io.github.classgraph:classgraph:jar is missing. @ line 134, column 21
```

It seems that `common` version picked by PR builder does not have your change: https://github.com/confluentinc/common/pull/624

**Comment by rahejaprince** [comment]
@kagarwal06 @janjwerner-confluent cp1 branch is cut from post branches which are created from the RC branches used to release a CP version. In this case, 7.7.0-cp1 branch is created from 7.7.0-post branch which contains version for common as 7.7.0. Now this version is not pushed by common repo to codeartifactory, they push versions with a nano version e.g. 7.7.0-5
These released version of format x.y.z are coming from the RC build which pushes the jar to S3 which are available at packages.confluent.io/maven/ 
Any change made in .x branches will never make it to jars in packages.confluent.io once the jar is released. So, in this case now, as ksqldb is depending on the jar which is not changing, you should pin the upgraded version here. Also, please avoid making any changes other than CVE version fixes and minor code changes in FEDRAMP related branches because of this issue.

**Comment by kagarwal06** [comment]
> @kagarwal06 @janjwerner-confluent cp1 branch is cut from post branches which are created from the RC branches used to release a CP version. In this case, 7.7.0-cp1 branch is created from 7.7.0-post branch which contains version for common as 7.7.0. Now this version is not pushed by common repo to codeartifactory, they push versions with a nano version e.g. 7.7.0-5 These released version of format x.y.z are coming from the RC build which pushes the jar to S3 which are available at packages.confluent.io/maven/ Any change made in .x branches will never make it to jars in packages.confluent.io once the jar is released. So, in this case now, as ksqldb is depending on the jar which is not changing, you should pin the upgraded version here. Also, please avoid making any changes other than CVE version fixes and minor code changes in FEDRAMP related branches because of this issue.

Thanks @rahejaprince for the explanation.
@janjwerner-confluent in that case, we can modify this PR to bump the version in ksql code itself (`<version>4.8.138</version>`). I don't have the code push permissions in the public repos. Can you please modify the PR? Thanks.

**Review by VedarthConfluent — APPROVED** [review]
lgtm

**Comment by rahejaprince** [comment]
cp-jar-build failure in semaphoreCI in this PR can be ignored as is not meant for hotfix/rc builds. In future, cp-jar-build will be disabled for PRs having base brach as hotfix branches

**Comment by kagarwal06** [comment]
Ksql build and tests are passing. 
image

Merging the PR(after referring @rahejaprince's comment)

**Pull request merged**
