### PR TITLE
Merge Conflict Resolution (from 7.0.x to 7.1.x)

### PR DESCRIPTION
**Pull request by ConfluentJenkins**
# What is this pull request?

This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).

# Next Steps

1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)

NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.

# Questions?
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall

### CODE REVIEW

**Review by pgaref — APPROVED** [review]

**Comment by rkhachatryan** [comment]
This change causes compilation failure:
```
ksql/ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryCleanupService.java:[142,56] incompatible types: java.lang.String cannot be converted to java.lang.Throwable
ksql/ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryCleanupService.java:[152,55] incompatible types: java.lang.String cannot be converted to java.lang.Throwable
```
The branch contains [more logging statements](https://github.com/confluentinc/ksql/blob/9b95f1c8a8f5285d1c2a4bbd0592d2e2279e05da/ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryCleanupService.java#L152) that weren't updated to use apache logging framework instead of log4j.

I'm wondering why was it necessary to switch the framework in the first place in #10125 ?

@mjsax, @pgaref

**Comment by mjsax** [comment]
Do you think the fix https://github.com/confluentinc/ksql/pull/10125 is not correct? Happy to resolve it differently.

**Comment by pgaref** [comment]
> This change causes compilation failure:
> 
> ```
> ksql/ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryCleanupService.java:[142,56] incompatible types: java.lang.String cannot be converted to java.lang.Throwable
> ksql/ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryCleanupService.java:[152,55] incompatible types: java.lang.String cannot be converted to java.lang.Throwable
> ```
> 
> The branch contains [more logging statements](https://github.com/confluentinc/ksql/blob/9b95f1c8a8f5285d1c2a4bbd0592d2e2279e05da/ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryCleanupService.java#L152) that weren't updated to use apache logging framework instead of log4j.
> 
> I'm wondering why was it necessary to switch the framework in the first place in #10125 ?
> 
> @mjsax, @pgaref

Good catch! We should probably revert since its breaking the build..
Wondering why we didnt see this when building/testing locally

**Comment by mjsax** [comment]
The original PR was against 7.0.x -- however, the Jenkins job on this PR should have failed? Did you check before merging?

I actually did a follow up to fix 7.1.x already: https://github.com/confluentinc/ksql/commit/e95fc82d43bccecde298da63881ae2469494f7bc and 7.1.x builds locally and on Jenkins.

Did pint-merge with `ours` so newer branches (7.2.x etc) don't have this change yet. Let's see what @rkhachatryan thinks before we continue.

**Comment by pgaref** [comment]
> The original PR was against 7.0.x -- however, the Jenkins job on this PR should have failed? Did you check before merging?
> 
> I actually did a follow up to fix 7.1.x already: [e95fc82](https://github.com/confluentinc/ksql/commit/e95fc82d43bccecde298da63881ae2469494f7bc) and 7.1.x builds locally and on Jenkins.
> 
> Did pint-merge with `ours` so newer branches (7.2.x etc) don't have this change yet. Let's see what @rkhachatryan thinks before we continue.

I am afraid our branch checks are a bit off (seem to work only for master?), also are we skipping tests entirely on builds [now](https://github.com/confluentinc/ksql/pull/10082/files)?

**Comment by mjsax** [comment]
Ouch... https://github.com/confluentinc/ksql/pull/10135

\cc @haoLiConfluent 

At least I now understand why `master` did not fail like other branches (was already very puzzled why we don't see the same test failures on `master` given that the code is the same... it drove me crazy...)

**Comment by tzulitai** [comment]
re: forward merging to newer 7.2+ branches

honestly - although I also don’t have a clue how and why it started failing, I don’t believe there’s going to be an issue with changing the logging framework
it’s confusing as it was that we were using different frameworks across test and prod code anyways …

I’d say +1 to apply this to newer branches 7.2.x and 7.3.x as well

**Pull request merged**
