### PR TITLE
fix git url ssh to https

### PR DESCRIPTION
**Pull request by dogHere**
fix this error:

```
ssh_exchange_identification: read: Connection reset by peer
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

### CODE REVIEW

**Comment by dogHere** [comment]
[clabot:check]

**Comment by miguno** [comment]
@dogHere : There's another `git@...` occurrence in `docs/contributing.md`.  Could you include this in your PR as well please?

@confluentinc/ksql: This PR is +1 from me once updated to change all gitssh-urls to https-urls.

**Comment by dogHere** [comment]
@miguno  Maybe ssh is better for a fork repository.

**Comment by dogHere** [comment]
@aayars @miguno Any problem?

**Pull request merged**
