### PR TITLE
chore: fix tests for strict retention

### PR DESCRIPTION
**Pull request by lucasbru**
### Description 

Upstream Kafka streams was changed to enforce strict retention, meaning that windows that are expired by the `RETENTION` clause of the window, but are still available inside the materialized `WindowStore` or `SessionStore` due to the segmented nature of RocksDB, will _not_ be returned anymore.

KSQL functional tests were checking for the original behavior of retention, where expired windows would still remain accessible when querying the materialization of a persistent query with a `RETENTION` clause. In this change, we update the expected behavior.

With the update to the new version of Kafka Streams, we change the externally visible behavior of KSQL, but the new behavior should be closer in line the expectations set by the KSQL documentation, so this is not expected to cause problems for users.

For the Kafka Streams change, see KAFKA-12960.

### Testing done 

Covered by CI.

### Reviewer checklist
- [x] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [x] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Review by Gerrrr — APPROVED** [review]
LGTM!

**Review by vvcephei — APPROVED** [review]

**Comment by vvcephei** [comment]
The test failures don't really make sense to me, so I kicked off the build again.

**Comment by lucasbru** [comment]
@vvcephei I think the test results make sense, in the context of enforcing strict retention. Note that joins set a retention period that is window_size + grace_period, so all records that are older than that will not be returned by window stores anymore in the new AK version. You can check the commit "update QTT results", where it's easier to see what changed about the join semantics.

For example, in the "INNER JOIN" test, the record with time 330000 advances stream time, so all records drop out of the window, so all records following the 330000 record won't have a join partner. Due to strict retention, the window store is looking completely empty when the out-of-order records are processed.

The question is - can we accept that the join semantics changes so drastically? And if we can, how can we deal with the fact that we will get different results for historical plans now?

**Comment by vvcephei** [comment]
Thanks, @lucasbru .

Based on my understanding of the upstream issue (KAFKA-12960), the results were actually incorrect before, and now they are correct. If that is the case, then I think the change is acceptable, even regarding historical plan results.

Based on your comment, it seems like you have been confirming the semantics of the tests you fixed. As long as that's the case, then I'd suggest that we just carry on and fix the remainder of the broken tests.

**Comment by lucasbru** [comment]
@vvcephei Okay, sorry for being a little hesitant here, I just wanted to have confirmation that we can change the result of historic queries. The upstream change does seem to move things into the right direction, so I'm going to update the tests and finally unblock the upgrade.

Anyway, I'm surprised by the join behavior in KSQL. I seem to get different event time for the left and the right side of the join, so it may be that records on the left side for time stamp 60000 are long expired, while records with time stamp 60000 on the right side are still being returned. Having expiration synchronized for both sides of the join seems more natural to me. But then again, this is not caused or fixed by the upstream changes, so I'm just going to unblock this.

**Pull request merged**
