### PR TITLE
Use correct / consistent upstream registry & tag

### PR DESCRIPTION
**Pull request by maxzheng**
Matches what ksql-server is using https://github.com/confluentinc/ksql/blob/master/cp-ksql-server/Dockerfile#L4

This will allow us to build images for different branches correctly, e.g. for RC tags. 
`mvn package -Pdocker` actually works after change for 5.0.0-rc3

### CODE REVIEW

**Comment by mohnishbasha** [comment]
I had a similar updated earlier but got reverted, looks like need some testing and validation.
https://github.com/confluentinc/ksql/pull/1604
https://github.com/confluentinc/ksql/pull/1605

**Comment by maxzheng** [comment]
@mohnishbasha ur change was missing the `ARG DOCKER_UPSTREAM_TAG`

**Comment by mohnishbasha** [comment]
you are right,  i missed that during updating the PR.

**Comment by maxzheng** [comment]
FYI This PR's build is green, which wasn't the case last time / the reason that @mohnishbasha PR had to be reverted.

**Comment by mohnishbasha** [comment]
Thanks for taking care of this @maxzheng.

**Pull request merged**
