### PR TITLE
Remove youtube link from clickstream

### PR DESCRIPTION
**Pull request by joel-hamill**
Removed dead link

### CODE REVIEW

**Comment by joel-hamill** [comment]
cc @ybyzek

**Comment by big-andy-coates** [comment]
How come we're removing the show cast in its entirety? It's a useful think to link to. Can we not just fix the link?

**Comment by bluemonk3y** [comment]
I dont think we should be removing it

**Comment by big-andy-coates** [comment]
The link in the main repo

**Comment by big-andy-coates** [comment]
I don't know, given this video is all about the user click stream demo, I think it still makes sense to link to it from this page too. But that's just my humble opinion =)

**Comment by bluemonk3y** [comment]
@joel-hamill  - this is the main page for the clickstream demo and IMO it the link showing it in action still belongs here ;) - sorry!

**Comment by joel-hamill** [comment]
Added demo back in, with workings links

**Pull request merged**
