### PR TITLE
feat: print worker properties to console when ksql server is starting

### PR DESCRIPTION
**Pull request by alex-dukhno**
### Description 
implementation of #3777 enhancement.
@ybyzek could you please take a look if I correctly understand your proposal in #3777?

### Testing done 
None for now. Just quick start of experiment.

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by alex-dukhno** [comment]
clabot:check

**Comment by ybyzek** [comment]
@alex-dukhno thanks for the PR.  In addition to printing the properties at start up (which actually may not be desirable -- there is no precedent for this right now in ksqlDB, is there?), it may be more useful to print the properties on demand, e.g. extend the command `print properties` to include Connect, e.g. `print properties connect` (just as an example).  WDYT?

**Comment by alex-dukhno** [comment]
@ybyzek thank you. I was thinking about adding command when clicked "create pr" button, but was not sure... I will work on adding the command.

Thank you.

**Comment by big-andy-coates** [comment]
Hey @alex-dukhno, it's probably worth raising a quick KLIP on the proposed extension to the SQL syntax.

**Comment by alex-dukhno** [comment]
@big-andy-coates thank you. I will try to work on PR for KLIP this week.

And closing this PR.

**Pull request closed without merging**
