### PR TITLE
MINOR: Cause 'ksql help' and 'ksql -help' to behave the same as 'ksql…

### PR DESCRIPTION
**Pull request by vcrfxia**
… -h' and 'ksql --help'

### Description 
_What behavior do you want to change, why, how does your patch achieve the changes?_

Fixes https://github.com/confluentinc/ksql/issues/1444, by redirecting 'ksql help' and 'ksql -help' to 'ksql --help'.

### Testing done 
_Describe the testing strategy. Unit and integration tests are expected for any behavior changes._

Verified that "ksql", "ksql-server-start", and "ksql-datagen" (the only three scripts affected by changes to "ksql-run-class") are as expected when run with each of the help flags.

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by vcrfxia** [comment]
[clabot:check]

**Comment by apurvam** [comment]
thanks @vcrfxia ! The changes look fine, but I am curious about how you tested this change.

**Comment by vcrfxia** [comment]
> thanks @vcrfxia ! The changes look fine, but I am curious about how you tested this change.

Besides checking that integration tests continue to pass, I verified that "ksql", "ksql-server-start", and "ksql-datagen" (the only three scripts affected by changes to "ksql-run-class") are as expected when run with each of the help flags. Are there other tests/checks I should perform? Thanks!

**Comment by apurvam** [comment]
Thanks @vcrfxia It would be good to add those details to the "Testing done" section.

**Pull request merged**
