### PR TITLE
Add UDF / UDAF quickstart Maven archetype

### PR DESCRIPTION
**Pull request by mitch-seymour**
### Description 
Resolves https://github.com/confluentinc/ksql/issues/2028.

This PR adds a Maven archetype that will allow users to quickly generate a project template for building custom UDFs / UDAFs.

__Note:__ I am not familiar with Confluent's process for publishing artifacts to the Confluent Maven repo (http://packages.confluent.io/maven/), though I did make an educated guess (see the instructions in the [quickstart README](https://github.com/confluentinc/ksql/blob/c2e3a24618a693c21ce2eb8ec04ccf94d183512f/ksql-udf-quickstart/README.md#deploy-artifacts)). So any help on that end would be greatly appreciated :)

### Testing done 
Testing was done manually via these steps:

#### Install custom functions
```
# install the new archetype locally
$ cd ksql-udf-quickstart/
$ mvn clean install

# make a directory for our generated project template
$ mkdir test && cd test

# generate the project template
$ mvn archetype:generate -X \
    -DarchetypeGroupId=io.confluent.ksql \
    -DarchetypeArtifactId=ksql-udf-quickstart \
    -DarchetypeVersion=5.2.0-SNAPSHOT \
    -DgroupId=com.mitchseymour.ksql.functions \
    -DartifactId=my-udf \
    -Dversion=0.1.0-SNAPSHOT

# build the UDF / UDAF JAR
$ cd my-udf/ && mvn clean package

# copy the JAR to the KSQL extension directory
$ cp target/my-udf-0.1.0-SNAPSHOT.jar /path/to/ext/

# start a local KSQL server
$ ./bin/ksql-server-start config/ksql-server.properties

# in another tab, start the CLI
$ ./bin/ksql
```

#### CLI verification
Verify the example functions exist and produce the expected output using the CLI.

```
ksql> DESCRIBE FUNCTION REVERSE ;

Name        : REVERSE
Overview    : Example UDF that reverses an object
Type        : scalar
Jar         : /tmp/ext/my-udf-0.1.0-SNAPSHOT.jar
Variations  :

	Variation   : REVERSE(VARCHAR)
	Returns     : VARCHAR
	Description : Reverse a string

	Variation   : REVERSE(INT)
	Returns     : VARCHAR
	Description : Reverse an integer

	Variation   : REVERSE(BIGINT)
	Returns     : VARCHAR
	Description : Reverse a long

	Variation   : REVERSE(DOUBLE)
	Returns     : VARCHAR
	Description : Reverse a double

ksql> DESCRIBE FUNCTION SUMMARY_STATS ;

Name        : SUMMARY_STATS
Overview    : Example UDAF that computes some summary stats for a stream of doubles
Type        : aggregate
Jar         : /tmp/ext/my-udf-0.1.0-SNAPSHOT.jar
Variations  :

	Variation   : SUMMARY_STATS(DOUBLE)
	Returns     : MAP<VARCHAR,DOUBLE>
	Description : compute summary stats for doubles


ksql>  CREATE STREAM api_requests (username VARCHAR, endpoint VARCHAR, response_code INT, response_time DOUBLE) \
WITH (kafka_topic='api_logs', value_format='JSON');

ksql > SELECT username, REVERSE(username), endpoint, SUMMARY_STATS(response_time) \
FROM api_requests \
GROUP BY username, REVERSE(username), endpoint ;
```

Now, in another tab, produce some dummy records to our topic, `api_logs`:
```
$ echo '{"username": "mseymour", "endpoint": "index.html", "response_code": 200, "response_time": 400}' | kafkacat -q -b localhost:9092 -t api_logs -P

$ echo '{"username": "mseymour", "endpoint": "index.html", "response_code": 200, "response_time": 900}' | kafkacat -q -b localhost:9092 -t api_logs -P 
```

Finally, check the function output in KSQL CLI

```
mseymour | ruomyesm | index.html | {sample_size=1.0, stddev_sample=0.0, mean=400.0, sum=400.0, sum_squares=160000.0, stddev_population=0.0}
mseymour | ruomyesm | index.html | {sample_size=2.0, stddev_sample=353.5533905932738, mean=650.0, sum=1300.0, sum_squares=970000.0, stddev_population=250.0}
...
```

The above results indicate that the custom UDF and UDAF included in the archetype work, and should therefore be a helpful reference for other devs wishing to use the archetype as a project template.

### Reviewer checklist
- [x] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [x] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### Open questions
- Should we manually rebuild the archetype on every new KSQL release, or automate this process somehow?
- Should we add more documentation around this project template (e.g. create a blog post and add it to the [Latest News](https://github.com/confluentinc/ksql#latest-news) section in the main README)? I'm happy to contribute a blog post if needed.

### CODE REVIEW

**Comment by big-andy-coates** [comment]
Thanks @mitch-seymour. I'm not a Maven person myself. I've pinged some people who are to take a look.  Thanks for your contribution!

**Comment by mitch-seymour** [comment]
Thanks @big-andy-coates! I saw that you mentioned in another PR that @hjafarpour might know about the packaging stuff? Anyways, I'll await further review from someone who can verify the deployment steps for this new Maven archetype :) Have a great weekend

**Comment by mitch-seymour** [comment]
@big-andy-coates one more thing, I'd love to contribute a guest blog post about how to use this new archetype if there's any opportunity to do so. If not, no worries. I created a proposal for what the blog post could include here in case it is possible though:

https://gist.github.com/mitch-seymour/6f6a0c66e7e33b34eb85776502da7047

**Comment by big-andy-coates** [comment]
Awesome, thanks @mitch-seymour.

**Comment by big-andy-coates** [comment]
@JimGalasyn there's some brief docs in here, plus once this is merged they'll be other docs that need updating, i.e. the ones for creating a new UDF using Maven.

**Comment by apurvam** [comment]
Thanks for the patch @mitch-seymour ! I just merged this. 

@JimGalasyn are you tracking the further docs updates that need to be made elsewhere?

**Comment by miguno** [comment]
Thanks for the PR, @mitch-seymour !

**Comment by mitch-seymour** [comment]
Thanks for the approvals :) I have a couple of quick follow up questions: 

- Now that this PR is merged, what is the process for publishing the archetype to the Confluent Maven repo? Will the tools team handle future deployments of this artifact? Also, is the snapshot version included in this PR available in a snapshots repo somewhere?
- Would there be any value in adding [this post](https://gist.github.com/mitch-seymour/6f6a0c66e7e33b34eb85776502da7047) to the Confluent blog once 5.2.0 is released? If not, then no worries :). Just wanted to put that out there in case it would be useful for others.

Thanks again for the 👀 :)

**Comment by JimGalasyn** [comment]
@apurvam , tracking doc update with internal ticket KSQL-2072.

**Comment by MichaelDrogalis** [comment]
Hey @mitch-seymour! Thanks for contributing this template. We're definitely interested in the blog piece. I'll drop you an email, per the one listed on your personal site.

**Pull request merged**
