### PR TITLE
test: fix SR incompatbility in RecordFormatterTest

### PR DESCRIPTION
**Pull request by agavra**
### Description 

SR made a change where internally they stopped using a method we mocked, this mocks the proper method

### Testing done 

ran the test

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Review by rayokota — APPROVED** [review]
LGTM, thanks @agavra

**Comment by rayokota** [comment]
Should this target 7.0.x?

**Review by vcrfxia — APPROVED** [review]
Thanks @agavra !

**Comment by agavra** [comment]
@rayokota yes you are right

**Pull request merged**
