### PR TITLE
Allow passing a properties file to the quickstart examples

### PR DESCRIPTION
**Pull request by mimaison**
Added propertiesFile argument to specify connection settings

### CODE REVIEW

**Comment by stephen-warwick** [comment]
I have signed the CLA on behalf of IBM United Kingdom Ltd, with Michael Maison and Edoardo Comar as contributors.

**Comment by mimaison** [comment]
[clabot:check]

**Comment by mimaison** [comment]
@miguno @hjafarpour Can you have a look please ?

**Comment by mimaison** [comment]
@miguno @hjafarpour Gentle reminder =)

**Comment by mimaison** [comment]
@miguno @hjafarpour I've let a few weeks pass now without a reply. Can you have a look ?
If you are not the correct reviewers, let me know. Thanks

**Comment by mimaison** [comment]
@miguno @hjafarpour @dguy Is there any reasons why this has not been looked at ?

**Comment by apurvam** [comment]
Sorry for the delay in looking at this at @mimaison . It looks good to me, but the patch needs to be targeted to master. Perhaps the best way its to create a local patch file, apply it on master, and then force update your PR branch.

**Comment by mimaison** [comment]
Thanks @apurvam. After updating my branch I tried updating the base branch of the PR but it made a mess !

So I opened a new PR https://github.com/confluentinc/ksql/pull/657 with the patch on top of master.

**Pull request closed without merging**
