### PR TITLE
refactor: remove unnecessary lock object and replace with synchronized

### PR DESCRIPTION
**Pull request by purplefox**
### Description 
Replaces an unnecessary explicit lock object with the synchronized keyword.

The lock was only adding clutter to the code and the behaviour was identical to making the methods synchronized.

### Testing done 

Run test suite

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by ijuma** [comment]
I don't know the original intent, but one difference is that the lock was previously encapsulated (i.e. external classes did not have access to the lock) and now it is not. Not sure it matters here though. Let's see what others say.

**Comment by purplefox** [comment]
Yes, that's a good point. If something elsewhere is doing `synchronized(metaStore) {...}` then the behaviour could be different. I did a quick search and couldn't find anything.

**Comment by cpettitt-confluent** [comment]
+1 @ijuma on this. It may even have been in Effective Java? Definitely in practice I've found that using locks internally is more defensive and future proof - e.g. we may not have any use now, but down the road as code shifts that assumption may not hold.

**Comment by purplefox** [comment]
My personal opinion is that `synchronized(lock)` should not be used unless there is a specific need for fine grained locking in the object.

Yes, there is a small possibility that an external piece of code is synchronizing on the object but this it's easy to verify that this is not the case in the codebase. If this was class was part of a published API that we wanted 3rd parties to use then this would be more of an issue (and I think Bloch's original insight alludes more to this case than ours).

But in that case it might be better to have a non synchronized public delegate which delegates to a synchronized implementation. That way we don't expose the lock to the user but we also keep the internal logic clean without ugly synchronized(lock) blocks adding eyestrain and unnecessary indentation. I.e. we could have our cake and eat it.

I think defensive programming can be a good principle, but like most things should be applied judicously and where appropriate. Taken too far the perceived benefits that it brings can be outweighed by the extra clutter that it introduces. (I think overuse of final is another example of this).

**Comment by purplefox** [comment]
Here are some more reasons why I think this pattern is a bad idea (apart from in public APIs):

A mutable class with lots of getters (or any class with lots of small methods, they don't have to be getters or setters). I hope you would agree this is super ugly and the explicit locking probably doubles the size of the code compared to using synchronize:

```
public class MyEyesAreBleeding {
  
  protected int a1;
  protected int a2;
  protected int a3;
  protected int a4;
  protected int a5;
  protected int a6;

  private final Object lock = new Object();
  
  public int doSomething1() {
    synchronized (lock) {
      return a1;
    }
  }

  public int doSomething2() {
    synchronized (lock) {
      return a2;
    }
  }

  public int doSomething3() {
    synchronized (lock) {
      return a3;
    }
  }

  public int doSomething4() {
    synchronized (lock) {
      return a4;
    }
  }

  public int doSomething5() {
    synchronized (lock) {
      return a5;
    }
  }

  public int doSomething6() {
    synchronized (lock) {
      return a6;
    }
  }

}
```

Second example. Can you spot the error?:

```
public class LockOnWrongObject {

  protected int a1;
  protected int a2;
  protected int a3;
  protected int a4;
  protected int a5;
  protected int a6;

  private Object lock = new Object();

  public int doSomething1() {
    synchronized (lock) {
      return a1;
    }
  }

  public int doSomething2() {
    synchronized (lock) {
      return a2;
    }
  }

  public int doSomething3() {
    synchronized (lock) {
      return a3;
    }
  }

  public int doSomething4() {
    synchronized (lock) {
      return a4;
    }
  }

  public int doSomething5() {
    synchronized (lock) {
      return a5;
    }
  }

  public int doSomething6() {
    synchronized (this) {
      return a6;
    }
  }
}
```

One of the methods is locking on the wrong object. Not so easy to spot if you have lots of methods.

Example 3: 

```
public class NonFinalLock {

  protected int a1;
  protected int a2;
  protected int a3;
  protected int a4;
  protected int a5;
  protected int a6;
  
  protected Object lock = new Object();

  public int doSomething1() {
    synchronized (lock) {
      return a1;
    }
  }

  public int doSomething2() {
    synchronized (lock) {
      return a2;
    }
  }

  public int doSomething3() {
    synchronized (lock) {
      return a3;
    }
  }

  public int doSomething4() {
    synchronized (lock) {
      return a4;
    }
  }

  public int doSomething5() {
    synchronized (lock) {
      return a5;
    }
  }

  public int doSomething6() {
    synchronized (lock) {
      lock = new Object(); // Oops, lock has been replaced, this could also happen in a subclass
      return a6;
    }
  }
}
```

In the above the author has forgotten to make the lock final and its been changed in a method (this could also happen more subtely in a subclass).

But even if the lock is final, how about this one? Here we have a superclass and subclass:

```
public class Superclass {
  
  protected int a1;
  protected int a2;
  protected int a3;
  protected int a4;
  protected int a5;
  protected int a6;

  private final Object lock = new Object();
  
  public int doSomething1() {
    synchronized (lock) {
      return a1;
    }
  }

  public int doSomething2() {
    synchronized (lock) {
      return a2;
    }
  }

  public int doSomething3() {
    synchronized (lock) {
      return a3;
    }
  }

  public int doSomething4() {
    synchronized (lock) {
      return a4;
    }
  }

  public int doSomething5() {
    synchronized (lock) {
      return a5;
    }
  }

  public int doSomething6() {
    synchronized (lock) {
      return a6;
    }
  }

}


public class Subclass extends Superclass {

  private final Object lock = new Object();


  public int doSomething1() {
    synchronized (lock) {
      return a1;
    }
  }

  public int doSomething2() {
    synchronized (lock) {
      return a2;
    }
  }

  public int doSomething3() {
    synchronized (lock) {
      return a3;
    }
  }

  public int doSomething4() {
    synchronized (lock) {
      return a4;
    }
  }

  public int doSomething5() {
    synchronized (lock) {
      return a5;
    }
  }

  public int doSomething6() {
    synchronized (lock) {
      return a6;
    }
  }


}
```

This is broken too, as the lock in the subclass shadows the lock object in the superclass.

I think there are lots of ways you can screw up with explicit locks and this pattern is likely to introduce more bugs than it claims to solve.

So, for me, the case against this pattern on that basis alone is quite strong and that's before taking into account the extra verbosity it introduces.

Another thing to consider is why does the Java language have the `synchronized` keyword in the first place? Pretty much the whole reason is to avoid this kind of pattern.

Just my 2c of course. I will happily close this PR if everyone disagrees with me. But please don't ask me to write code in this way! :)

**Comment by purplefox** [comment]
I'm going to close this as it doesn't seem popular.

**Pull request closed without merging**
