### PR TITLE
Update insert-into.md

### PR DESCRIPTION
**Pull request by aurabhi**
### Description 
_What behavior do you want to change, why, how does your patch achieve the changes?_

### Testing done 
_Describe the testing strategy. Unit and integration tests are expected for any behavior changes._

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Review by spena — APPROVED** [review]
+1

**Comment by spena** [comment]
Thanks @aurabhi for the doc fix.

**Comment by JimGalasyn** [comment]
Thanks, @aurabhi and @spena! I cherry-picked to `0.15.0-ksqldb`, `0.15.x-ksqldb`, `0.16.x-ksqldb`, and `6.2.x`.

**Review by JimGalasyn — COMMENTED** [review]
Thank you!

**Pull request merged**
