### PR TITLE
Single field serialization Part II

### PR DESCRIPTION
**Pull request by big-andy-coates**
### Description 

Following on from #2800, this PR looks to address the following outstanding tasks from that PR:

* 2. Switch the default so that by default we unwrap single values.

In addition, when adding the new compatibility breaking config many existing tests QTT tests failed, as the actual output form had changed, (single fields where no longer being wrapped).   Changing the tests to not expect the output to be wrapped worked for the latest version of the tests, but failed for previous version, (i.e. those listed in `expected_topologies` dir), as they have their persisted config restored.  

Rather than add a property to each test to to ensure values are unwrapped/wrapped, (which would mean over time as more compatibility breaking configs are added that the set of properties each test will need will grow), I've changed QTT to automatically apply the _latest_ default for any compatibility breaking config that didn't exist when the configs were captured.  This allows _existing_ tests to be changed inline with current functionality. Obviously, new tests should be added to cover the affect of the config.

### Testing done 

The usual

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by hjafarpour** [comment]
@big-andy-coates I thought we agreed to not have a default and only use the explicit format from `WITH` clause and it it is not specified use the same format from the source. Haven't looked into the code yet but just wanted to confirm this before looking into the code.

**Comment by big-andy-coates** [comment]
Hi @hjafarpour 

> @big-andy-coates I thought we agreed to not have a default and only use the explicit format from WITH clause and it it is not specified use the same format from the source. Haven't looked into the code yet but just wanted to confirm this before looking into the code.

That's not my understanding at all. I understood that we'd agreed that we'd have a config that controls the default behaviour, and then have syntax to allow the user to change this on a per-command basis, (which will come in a later PR).

@agavra, what's your recollection?

**Comment by agavra** [comment]
@hjafarpour @big-andy-coates, my recollection is that the hierarchy is WITH > source > config, but that we have all three. The confusion may be around  that the config should _never_ apply to CTAS/CSAS statements (only to CT/CS statements) since there will always be a source setting to propagate

**Comment by big-andy-coates** [comment]
... the bit about the config _never_ being applied to CTAS / CSAS statements is in the next PR.

**Pull request merged**
