### PR TITLE
docs: update changelog for 0.22 release #8315

### PR DESCRIPTION
**Pull request by mjsax**
Replaces #8315 to change target branch from `master` to `0.22.x-ksqldb`

### CODE REVIEW

**Review by JimGalasyn — APPROVED** [review]
LGTM!

**Comment by mjsax** [comment]
@JimGalasyn -- `0.22.0-ksqldb` exists already -- guess we need to manually merge into it, too?

**Comment by JimGalasyn** [comment]
@mjsax sadly yes, since we don't have pint merge for the `*-ksqldb` branches.

**Comment by mjsax** [comment]
Merged and cherry-picked to `0.22.0-ksqldb` branch.

**Pull request merged**
