### PR TITLE
refactor: remove final params and local variables from ksql-execution

### PR DESCRIPTION
**Pull request by purplefox**
### Description 

This PR removes final parameters and local variables from the ksql-execution module, as agreed by team.

Instead of doing the whole project in one go, I am doing this a module at a time to minimise disruption.

### Testing done 

Non functional change

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by hjafarpour** [comment]
@purplefox can you provide some context on this?
I'm sure @big-andy-coates would argue the opposite! ;)

**Comment by agavra** [comment]
@hjafarpour see discussion on #3642

**Comment by purplefox** [comment]
It was discussed at length here https://github.com/confluentinc/ksql/pull/3642 , and we also discussed it at length during a team meeting. The overall consensus was we should revert to company standard. @apurva agreed too.

I know not everyone agrees with this (@big-andy-coates in particular) but we can't always get unanimity for every team decision even though we would like that.

**Comment by purplefox** [comment]
And look how lighter and cleaner the code looks now, after the refactor :)

**Comment by big-andy-coates** [comment]
Why was this PR merged with two blocking reviews?

This is causing merge hell for a lot of people for no benefit.  It's one thing to say we're removing the need to have `final`. But there's no need to blanket change the code.

**Comment by purplefox** [comment]
I didn't make any changes to final in the directories that @rodesai requested to leave alone, so there shouldn't be any conflicts for him.

I am just executing on what we agreed upon as a team.

**Comment by purplefox** [comment]
I think it's important that team decisions are respected. We can't always have unanimous approval every time.

**Pull request merged**
