### PR TITLE
chore: update code for new AK release

### PR DESCRIPTION
**Pull request by agavra**
### Description 
* change usages of `AdminClient` to `Admin` for sandbox proxy
* change usages of `Total` to `CumulativeSum` to avoid deprecation
* change usages of `Count` to `WindowedCount` to avoid deprecation

This change will not be able to go through until https://github.com/apache/kafka/pull/7110 is merged and packaged with kafka-css

### Testing done 

- Will test when the above condition is met

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by ijuma** [comment]
The Admin change isn't required, right?

**Comment by ijuma** [comment]
To be clear, it's a good change, just good to be clear that the build continues to work with AdminClient too

**Comment by agavra** [comment]
@ijuma - our SandboxAdminClientTest fails because it only looks through declared public methods (not inherited methods). I agree this technically has nothing to do with backwards compatibility, but I figured I may as well fix the test in the "right" way by piping `Admin` all the way through

**Comment by ijuma** [comment]
I see. Makes sense.

**Comment by ijuma** [comment]
Build is green now.

**Comment by big-andy-coates** [comment]
Reverted as the Kafka snapshot builds have yo-yo'd again and no longer have these new types ::(

**Comment by ijuma** [comment]
I don't think you should have reverted this.

**Pull request merged**
