### PR TITLE
chore: fix broken test (#10125)

### PR DESCRIPTION
**Pull request by mjsax**
Cherry-pick of https://github.com/confluentinc/ksql/pull/10125

### CODE REVIEW

**Review by lucasbru — APPROVED** [review]
lgtm, thanks

**Comment by mjsax** [comment]
We got 6 test failures:

[io.confluent.ksql.rest.integration.PullQueryRoutingFunctionalTest.shouldFilterLaggyServers](https://jenkins.confluent.io/job/Confluent%20Public%20Repo%20PR%20builder/job/ksql/job/PR-10143/1/testReport/junit/io.confluent.ksql.rest.integration/PullQueryRoutingFunctionalTest/shouldFilterLaggyServers/)
[io.confluent.ksql.rest.integration.PullQueryRoutingFunctionalTest.shouldQueryWS](https://jenkins.confluent.io/job/Confluent%20Public%20Repo%20PR%20builder/job/ksql/job/PR-10143/1/testReport/junit/io.confluent.ksql.rest.integration/PullQueryRoutingFunctionalTest/shouldQueryWS/)
[io.confluent.ksql.rest.integration.PullQueryRoutingFunctionalTest.shouldQueryActiveWhenActiveAliveQueryIssuedToStandby](https://jenkins.confluent.io/job/Confluent%20Public%20Repo%20PR%20builder/job/ksql/job/PR-10143/1/testReport/junit/io.confluent.ksql.rest.integration/PullQueryRoutingFunctionalTest/shouldQueryActiveWhenActiveAliveQueryIssuedToStandby/)
[io.confluent.ksql.rest.integration.TransientQueryResourceCleanerIntTest.shouldNotCleanupTopicsOfRunningQueries](https://jenkins.confluent.io/job/Confluent%20Public%20Repo%20PR%20builder/job/ksql/job/PR-10143/1/testReport/junit/io.confluent.ksql.rest.integration/TransientQueryResourceCleanerIntTest/shouldNotCleanupTopicsOfRunningQueries/)
[io.confluent.ksql.rest.integration.TransientQueryResourceCleanerIntTest.shouldCleanupLeakedTopics](https://jenkins.confluent.io/job/Confluent%20Public%20Repo%20PR%20builder/job/ksql/job/PR-10143/1/testReport/junit/io.confluent.ksql.rest.integration/TransientQueryResourceCleanerIntTest/shouldCleanupLeakedTopics/)
[io.confluent.ksql.rest.integration.TransientQueryResourceCleanerIntTest.shouldCleanupLeakedStateDirs](https://jenkins.confluent.io/job/Confluent%20Public%20Repo%20PR%20builder/job/ksql/job/PR-10143/1/testReport/junit/io.confluent.ksql.rest.integration/TransientQueryResourceCleanerIntTest/shouldCleanupLeakedStateDirs/)

Not sure flaky or not. Will re-trigger build.

**Comment by mjsax** [comment]
Same tests failed again...

**Comment by mjsax** [comment]
7.2.x is green in the mean time. Closing this PR

**Pull request closed without merging**
