### PR TITLE
Move docker image to break circular dependency

### PR DESCRIPTION
**Pull request by vvcephei**
The docker image build was moved out of this repo in the 5.2.x branch to break a circular dependency, but the circular dependency was already present in the 5.1.x branch. This PR corrects the issue.

### CODE REVIEW

**Comment by vvcephei** [comment]
Just getting the PR started to see what happens with the build.

**Comment by vvcephei** [comment]
I've moved the images to https://github.com/vvcephei/ksql-images/tree/5.1.x , but there are a couple of problems...

The big blocker is that I can't create a PR to create a _new_ branch. I need a committer to create the 5.1.x branch on https://github.com/confluentinc/ksql-images

@rodesai , can you help out?

**Comment by vvcephei** [comment]
Also, I'm not sure why the build failed. It failed on Twistlock being unable to find `368821881613.dkr.ecr.us-west-2.amazonaws.com/confluentinc/ksql-cli:PR-3002-3`, but during the actual package phase, I see it claimed it actually did successfully tag the image.

Ideas?

**Comment by rodesai** [comment]
> The big blocker is that I can't create a PR to create a new branch. I need a committer to create the 5.1.x branch on https://github.com/confluentinc/ksql-images

@vvcephei you are already an admin for ksql-images.

> Also, I'm not sure why the build failed. It failed on Twistlock being unable to find 368821881613.dkr.ecr.us-west-2.amazonaws.com/confluentinc/ksql-cli:PR-3002-3, but during the actual package phase, I see it claimed it actually did successfully tag the image.

The twistlock is something the @confluentinc/tools team merged a few days ago. Can someone from there comment on this?

**Comment by ewencp** [comment]
Did you check if the image was still there? There's always a chance something caused it to be cleaned up during the build. Didn't check thoroughly, but pull failed for me.

Also, /cc @xiangxin72 who might have additional insight.

**Comment by xli1996** [comment]
@vvcephei Can you provide me the logs that twistlock failed? It may caused by either that the image is cleaned or wrong tags.

**Comment by vvcephei** [comment]
@xli1996 , thanks for taking a look. Here's the logs: https://jenkins.confluent.io/job/confluentinc-pr/job/ksql/job/PR-3002/3/consoleText

Fair warning, I am not familiar with this build at all, so we may need to do some sleuthing to figure how how it's _supposed_ to go.

**Comment by xli1996** [comment]
I don't see major difference between #2059 and this one, and the master branch works fine. The logs claims that the image is built successfully, maybe I will try disable twistlock temporary with `dockerScan=false` to see whether it can be uploaded to ECR, since if the twistlock scan failed, it will block images be uploaded.

**Comment by xli1996** [comment]
The twistlock issue seems to be flaky, no idea what really the issue is. Maybe spend some time later to investigate, but @vvcephei the build is green now.

**Comment by spena** [comment]
@vvcephei @rodesai is this PR ready to be merged?

**Comment by vcrfxia** [comment]
Merging to fix the build.

**Comment by vvcephei** [comment]
Hey, thanks, all. Sorry, I haven't checked in since your comments. I'll follow up and make sure that the image build gets added to the ksql-images repo.

**Pull request merged**
