### PR TITLE
Keep copy of rst docs for merge

### PR DESCRIPTION
**Pull request by ewencp**

### CODE REVIEW

**Comment by ewencp** [comment]
This should fix the merging issue -- it keeps a copy of the rst docs (which I moved in the 4.1.x branch and then merged just that change into master). This solution isn't ideal, but works for now and is better than risky merges. Just getting the files interpreted as deleted doesn't work because then git-merge doesn't want to accidentally let you lose changes so it leaves those files in a conflict state. And I couldn't find a flag for git-merge to override that behavior (which is probably the right choice generally).

The PR will look like just a ton of additions, but looking at git directly shows that commit is properly handled as just moving all the files:

screen shot 2018-03-20 at 2 13 13 pm

**Comment by apurvam** [comment]
Thanks for the update @ewencp . So for my understanding, the move from `docs` to `docs-rst` on 4.1.x is temporary. The ultimate location for the `.rst` docs on `4.1.x` will be `docs/`. But this temporary move is enough to satisfy git that the `.rst` files belong in `docs-rst` on master?

**Comment by ewencp** [comment]
Sorry, I was unclear -- this is going to `master`, I just started from `4.1.x` to do the move since it has the rst files still, then merged that into `master` and resolved remaining issues that git was confused about moves vs deletes. So this will result in only `docs/` in 4.1.x with rst content,  `docs/` and `docs-rst/` on `master` with md and rst content respectively, and when you make changes to `4.1.x` docs they will merge cleanly and appear in the `docs-rst/` folder on master.

This will be temporary, and when we are ready to we can simply delete the `docs/` directory in `master`, then move the `docs-rst/` directory back into place, and merging should continue to work normally.

**Comment by ewencp** [comment]
Merged externally b/c I actually wanted to preserve the merge and this repo is only allowing squash.

**Comment by dguy** [comment]
Thanks @ewencp!

**Pull request merged**
