### PR TITLE
docs: add note about singular time units (DOCS-13323)

### LINKED ISSUE #8971: TIMESTAMPSUB does not work for singular names of time units, eg. DAY, MINUTE,HOUR
**Describe the bug**
[timestampsub](https://docs.ksqldb.io/en/0.24.0-ksqldb/developer-guide/ksqldb-reference/scalar-functions/#timestampsub) does not work for singular names of time units, eg. DAY, MINUTE,HOUR. However the docs for [timeunit](https://docs.ksqldb.io/en/latest/reference/sql/time/#time-units) reads it allows singular names, eg DAY, HOUR, MINUTE
Is this a bug or just docs update as plural works for time units eg, DAYS, HOURS, MINUTES?

**To Reproduce**
select rowtime, timestampsub(MINUTE, 1, from_unixtime(rowtime)) from PWCTEST emit changes;
Line: 1, Col: 30: SELECT column 'MINUTE' cannot be resolved.
Statement: select rowtime, timestampsub(MINUTE, 1, from_unixtime(rowtime)) from PWCTEST emit changes;

**Expected behavior**
As per the docs singular minute should work.

**Actual behaviour**
Singular name does not work for time units
Line: 1, Col: 30: SELECT column 'MINUTE' cannot be resolved.
Statement: select rowtime, timestampsub(MINUTE, 1, from_unixtime(rowtime)) from PWCTEST emit changes;

### PR DESCRIPTION
**Pull request by JimGalasyn**
Fixes #8971.

Add note to time functions:

image

### CODE REVIEW

**Comment by Gerrrr** [comment]
WDYT about removing singular time units from https://docs.ksqldb.io/en/latest/reference/sql/time/?

**Comment by JimGalasyn** [comment]
@Gerrrr That's a good idea if we won't have a fix soon. If we're fixing it in the next version, I'm inclined to leave them, wdyt?

**Comment by Gerrrr** [comment]
A PR that introduces plural time units is open since October 2021 - https://github.com/confluentinc/ksql/pull/8284, but it introduces a breaking change. @jzaralim do you know if we are going to merge it?

**Comment by Gerrrr** [comment]
^ ping @jzaralim

**Review by jzaralim — APPROVED** [review]
We're not planning to merge the fix it for now

**Comment by Gerrrr** [comment]
Thanks @jzaralim! @JimGalasyn Since the singular units are unsupported, I suggest removing them from https://docs.ksqldb.io/en/latest/reference/sql/time/ rather than making notes for individual UDFs.

**Comment by JimGalasyn** [comment]
Thanks, @jzaralim and @Gerrrr!

**Comment by JimGalasyn** [comment]
Fixes #8971.

**Pull request merged**
