### PR TITLE
Make it clear what props are default values.

### PR DESCRIPTION
**Pull request by big-andy-coates**
### Description 
Fixes: #1920

The idea here is that the `list properties` call should make it clear what properties are at their default value.  We already have a marker for `LOCAL OVERRIDE`. I've added a new `DEFAULT` marker for those properties that are not set via server config or have local overrides.

So you now get an output like:

```
ksql> LIST PROPERTIES;

 Property                                               | Value
------------------------------------------------------------------------------------------------------------------------------------
[...]
 ksql.streams.auto.offset.reset (DEFAULT)                | latest
[...]
```

Not sure if we should also add a `SERVER OVERRIDE` tag too...?

### Testing done 
Added tests plus manual

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by rmoff** [comment]
1. How about "Effective Value" as the column heading?

2. Either (a) add "source" as a third column and list default/session/sever or (b) after the value mark those that are session/server overriden and leave those default ones with none—the point being to not clutter the display too much. Either way, I think the indicator should be against the value rather than the property label


    Option a: 

        ksql> LIST PROPERTIES;

        Property                                               | Effective Value | Default override
        ------------------------------------------------------------------------------------------------------------------------------------
        [...]
        ksql.some.other.test.property                          | latest          | 
        ksql.streams.auto.offset.reset                         | latest          | SESSION
        ksql.foo.bar.bork.bork.bork                            | latest          | SERVER
        ksql.some.test.property                                | latest          | 
        [...]

    Option b: 

        ksql> LIST PROPERTIES;

        Property                                               | Effective Value 
        ------------------------------------------------------------------------------------------------------------------------------------
        [...]
        ksql.some.other.test.property                          | latest          
        ksql.streams.auto.offset.reset                         | latest (SESSION OVERRIDE)
        ksql.foo.bar.bork.bork.bork                            | latest (SERVER OVERRIDE)
        ksql.some.test.property                                | latest         
        [...]

**Comment by big-andy-coates** [comment]
Output now has the override column:

```
 Property                                               | Default override | Effective Value                                               
-------------------------------------------------------------------------------------------------------------------------------------------
 ksql.extension.dir                                     |                  | ext                                                           
 ksql.functions.substring.legacy.args                   |                  | false                                                         
 ksql.output.topic.name.prefix                          |                  |                                                               
 ksql.persistent.prefix                                 |                  | query_                                                        
 ksql.schema.registry.url                               |                  | http://localhost:8081                                         
 ksql.service.id                                        |                  | default_                                                      
 ksql.sink.partitions                                   |                  | 4                                                             
 ksql.sink.replicas                                     |                  | 1                                                             
 ksql.sink.window.change.log.additional.retention       | SYSTEM           | 1000001                                                       
 ksql.statestore.suffix                                 |                  | _ksql_statestore                                              
 ksql.streams.application.id                            | SYSTEM           | KSQL                                                          
 ksql.streams.auto.offset.reset                         | SESSION          | latest                                                        
 ksql.streams.bootstrap.servers                         | SYSTEM           | 127.0.0.1:52970                                               
 ksql.streams.cache.max.bytes.buffering                 | SYSTEM           | 0                                                             
 ksql.streams.commit.interval.ms                        | SYSTEM           | 0                                                             
 ksql.streams.default.deserialization.exception.handler | SYSTEM           | io.confluent.ksql.errors.LogMetricAndContinueExceptionHandler 
 ksql.streams.num.stream.threads                        | SYSTEM           | 4                                                             
 ksql.transient.prefix                                  |                  | transient_                                                    
 ksql.udf.collect.metrics                               |                  | false                                                         
 ksql.udf.enable.security.manager                       |                  | true                                                          
 ksql.udfs.enabled                                      | SYSTEM           | false                                                         
 ssl.cipher.suites                                      |                  | NULL                                                          
 ssl.enabled.protocols                                  |                  | TLSv1.2,TLSv1.1,TLSv1                                         
 ssl.endpoint.identification.algorithm                  |                  | https                                                         
 ssl.key.password                                       |                  | NULL                                                          
 ssl.keymanager.algorithm                               |                  | SunX509                                                       
 ssl.keystore.location                                  |                  | NULL                                                          
 ssl.keystore.password                                  |                  | NULL                                                          
 ssl.keystore.type                                      |                  | JKS                                                           
 ssl.protocol                                           |                  | TLS                                                           
 ssl.provider                                           |                  | NULL                                                          
 ssl.secure.random.implementation                       |                  | NULL                                                          
 ssl.trustmanager.algorithm                             |                  | PKIX                                                          
 ssl.truststore.location                                |                  | NULL                                                          
 ssl.truststore.password                                |                  | NULL                                                          
 ssl.truststore.type                                    |                  | JKS                                                           
-------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by miguno** [comment]
@big-andy-coates : What do "SYSTEM" and "SESSION" refer to?  IMHO it's not self-explanatory.

I suppose:
- SYSTEM = Server configuration file
- SESSION = `SET` command

?

**Comment by big-andy-coates** [comment]
@miguno Cor, you're quick of the mark today!

I've already swapped `SYSTEM` -> `SERVER`, i.e. server config.

`SESSION` is your local CLI session.

**Comment by miguno** [comment]
@big-andy-coates : Ack.  I synced with @rmoff offline.  Let's go with the (updated) suggestion of SERVER and SESSION!

**Pull request merged**
