### PR TITLE
Make command topic compacted. send <key,null> when streams etc are dropped

### PR DESCRIPTION
**Pull request by dguy**
make command topic compacted. 
send <key,null> when streams etc are dropped.
skip drop statement when executing prior commands.
remove terminate command.
terminate persistent queries when a stream or table is dropped
#454

### CODE REVIEW

**Comment by dguy** [comment]
There is one thing i can think of that is missing here - that is the ability to remove the drop and terminate commands from the compacted log. There may be other things, too. I'm not exactly sure how the terminate command interacts with previous commands, i.e, should anything be dropped when a query is terminated?

**Comment by hjafarpour** [comment]
@dguy There is one more fundamental issue that we need to address before being able to use compaction. The query Id is assigned deterministically as an incrementing number. This is done in the engine and used for detecting the streams app id. If we remove some of the queries, the id assigner in the engine would not work correctly and queries will receive incorrect id in the new node that reads the command topic from the beginning.
So we can consider two options: come up with a naming scheme for the queries that does not depend on the order of the queries or perform compaction in KSQL layer.

**Comment by apurvam** [comment]
@hjafarpour raises a good point. We certainly should delegate compaction to Kafka and should not do that in the KSQL layer.

Why can't we write the query id as part of the message in the command topic itself at the time when it is created? This seems like a simple way to solve this problem right? The query id could just be an `int64` or something.

**Comment by apurvam** [comment]
Note that there is a bug with the existing logic: if queries are not created for one entire retention period, the next query will reuse and old id, causing the jobs to interfere with each other. 

For a 7 day retention, this shouldn't matter. But if this is overridden to be lower (for example, at the kafka cluster level), then it is possible that people will hit this.

**Comment by hjafarpour** [comment]
@apurvam at the moment query id is an `int64` and is created in the engine since we use it in all of the execution modes including embedded and application modes where we do not have command topic. Also for multiquery statement such as `Run Script` where we pass several queries in one message we need to assign independent ids to each query in the message. So there is no one to one relation between command topic messages and the query ids.

**Comment by dguy** [comment]
@apurvam compaction is done in kafka, but that doesn't mean that it has necessarily run. So you still need to remove the dups when reading the history.
I'm not sure how queryId is related here, but i guess i'll have to dig around and find out.

**Comment by dguy** [comment]
@hjafarpour let me see if i understand the reference to the `queryId` - this gets created/incremented in `QueryEngine` each time we create and execute a query. This is expected to be the same across all engines as it is used to terminate/check status etc of queries?
So it would seem to me that we need to move this out of the `QueryEngine` and into the `Command` as @apurvam suggested. We would also need to somehow push the `queryId` through for non-server mode. Or we just always use a `commandStore` but just have one for local mode that isn't backed by kafka.

**Comment by hjafarpour** [comment]
@dguy yes, that's the way queryId is assigned now. One extra think to remember is that for `run script` command we send one message but with multiple queries.

**Comment by dguy** [comment]
@hjafarpour thanks. Yes i've been looking through the code to see how it used. It might be that instead of using a long as the `queryId` we could create a `QueryId` class that has two fields, a `long`, and an `int`, the long would be assigned by the command or elsewhere it is constructed and the `int` would be assigned in the method(s) were multiple queries are executed.
Do you think that would work? Are there any other gotchas i need to be aware of?

**Comment by dguy** [comment]
@bluemonk3y @hjafarpour @apurvam i've extracted a `QueryId` class and the `QueryId` is always provided externally. So if we use the command topic then it is sent along with the `Command`, this way we know that we are always executing the same query. You'll see the `QueryId` is a `long` and an `int` - the `int` is so we can handle the run-script case.
There may be something else that needs to go in here as I know @bluemonk3y has been looking into it.
Oh, and the build will likely fail on CLiTest, they work individually but for some reason fail when all run together (I'm looking into it)

**Comment by hjafarpour** [comment]
@dguy I tried to run the quickstart queries and it seems that only one ID is assigned to queries. The first query gets 0-0 id and when I send the second query it gets the same id and I can only see the latest query in the results of `SHOW QUERY`

**Comment by dguy** [comment]
Thanks @hjafarpour i'll look into it

**Comment by dguy** [comment]
I've updated this and is all looking good. I've removed the terminate command in favour of using `drop stream blah` or `drop table blah` as when you terminate a persistent query you should also `drop` the relevant table/stream and vice versa. It also seems more natural to just use drop.
What may need to be done is when `drop stream` or `drop table` runs it should probably also drop/terminate all persistent queries that are dependent on it

**Comment by hjafarpour** [comment]
@dguy in general we should not have a 1-1 relation between Stream/Table and queries therefore we need terminate command to manage queries independently. Although at the moment we do not support `[IF NOT EXISTS]` in our `CREATE` statements, we already have it in our grammar and we should consider supporting it in near future. As an example consider the case where we have the following query:

`CREATE STREAM sinkStream AS SELECT * FROM sourceStream WHERE col1 = 'value1';`

This will create a new stream, `sinkStream`. Now consider I wanna change the logic of my query to include another filter. I should be able to just terminate the first query, issue a new query as the following:

`CREATE STREAM IF NOT EXISTS sinkStream AS SELECT * FROM sourceStream WHERE col1 = 'value1' AND col2 = 'value2';`

We won't be able to do this if we don't have `terminate`.

**Comment by dguy** [comment]
@hjafarpour presently if you terminate the query the stream you have created is useless. If you want to actually do anything with the same stream name you have to drop and re-create the stream. There is no way to restart the stream. 

In the existing code, if you were to terminate and recreate - using your example:
```
CREATE STREAM sinkStream AS SELECT * FROM sourceStream WHERE col1 = 'value1';
terminate query 1
drop stream sinkStream
create stream sinkStream AS SELECT * FROM sourceStream WHERE col1 = 'value1' AND col2 = 'value2';
```

With this change:
```
CREATE STREAM sinkStream AS SELECT * FROM sourceStream WHERE col1 = 'value1';
drop stream sinkStream;
create stream sinkStream AS SELECT * FROM sourceStream WHERE col1 = 'value1' AND col2 = 'value2';
```

So it is simpler and makes more sense to remove terminate and just use drop. If we have a legitimate need for it in the future we can add it back, but as it stands it doesn't work correctly and as far as i can tell it isn't needed for where we are at now. We need to stop adding code that we might need in the future.

**Comment by bluemonk3y** [comment]
@hjafarpour I'm in favour of removing terminate and simplifying the UX; this also brings us closer to std sql. 

We either need to handle query lifecycle properly OR hang them off of the related stream/table.  ATM we have a halfway house where its impossible to manage create them independently but you still have to terminate dangling queries (after a drop). For now, and given the amount of work in front of us, I would favour simplification *(until we know/learn more and can prioritise the work accordingly)

**Comment by hjafarpour** [comment]
I understand the argument in favor of simplicity but I am in favor of @bluemonk3y 's first suggestion which is `handling query lifecycle properly`. Here is my proposal:
We should have a n:1 relationship between queries and stream/table. Each query can write to only one stream/table but multiple queries can write into one stream/table. This is the same behavior in existing relational systems. We add `IF NOT EXISTS` to our CSAS/CTAS statements which we already have it in our grammar and provide the consistent behavior similar to CTAS in relational systems. This is a relatively low LOE and can be done very soon.
When we drop a stream/table we first terminate the queries that write into this stream/table and then drop it. If we have one or more queries writing into a stream/table when we terminate a query we leave the stream/table and just terminate the selected query and if we have other queries writing to the same stream/table, they will continue running.
One more point is that Stream/Table are data source/sinks while queries are computations. Although they are related we should not tightly couple them and we should have the possibility of managing them based on the context. Consider the following example in relational systems:
We can have multiple concurrent queries (insert/update/delete) writing to the same table and they can start and stop independently without requiring to drop the table.

**Comment by apurvam** [comment]
Regarding @hjafarpour first message: These ideas of n:1 relationship between queries and streams/tables seems premature. we would have to validate the schemas match for starters. And then the semantics would be really complicated when you have multiple writers into a stream or table. 

As for your analogy to relational databases, those are point in time inserts / updates which are much easier to reason about than multi-writer streaming inserts and updates. Do we really want to support the latter? How would people use them practically in a production context? What applications need them? What semantics would those applications require to be reliable? Can we guarantee those semantics with multiple writers? 

I think this isn't something we should jump into just because the implementation may be simple as of now. In fact, I think we should think about how to limit our promises at this point.

So having said that, I think @dguy's proposal is a good one. We keep a 1-1 mapping between queries and streams/tables, and remove the number of steps it takes to 'drop' a stream and/or table. This is kind of thing would be in line with simplifying our interfaces and improving user experience. 

We can have a conversation about supporting multi-writer tables and streams separately, but I honestly don't think it is something we should do any time soon unless we see a compelling use case. Again, let's simplify and focus on getting what we already have out there working very well. There is _a lot_ of work to do in the latter department IMO.

**Comment by apurvam** [comment]
> If we have two servers that submit two CTAS queries, one each (q1, q2) that create a table named t1 and both submit the query at the same time the commands for these two queries will have the same key and the query for the second user (q2) will be the latest message and would override the first query (q1). This is a wrong behavior.

Isn't this a general problem with the model? If I submit two queries creating the same table concurrently on two different nodes, isn't that a race? What would happen today? Would the last write win? How do we protect against it today?

**Comment by hjafarpour** [comment]
@apurvam In the current implementation, both statements will be written into the command topic and the first one will be executed and the second one will fail. We will know we had two statements and which one failed and we will always have a trace of the behavior. On the other hand if we assign id before writing the statement into the command topic, Kafka may perform compaction and all nodes can read and execute the second statement without even knowing there was another statement. In this way we loose the trace and won't be able to detect there was two statements.

**Comment by apurvam** [comment]
I see. Is the command topic a single partition?

**Comment by apurvam** [comment]
I guess what I don’t get is how the present scheme protects against conflicting statements like those which create the same stream or table. 

My understanding is that when a node gets a CTAS type statement, it checks if the stream exists in the metastore and fails the incoming query if so. If not, it writes the command to the metastore and then assigns a new query id. Other nodes will read the command from the command topic and assign the same query id and hence create another instance of the same streams application. 

The problem is that there is always going to be a lag between the producer on one node and the consumer on the other. So if the statement  to create the same stream happens simultaneously on two nodes, both meta stores will be empty,  both commands will be written, and then both statements will have different ids. This will probably corrupt the target stream. 

Is there something wrong with my understanding?

**Comment by hjafarpour** [comment]
@apurvam the command topic has one partition. The query id is assigned by all nodes after they read statements from the command topic. Since the command topic has only one partition the order in which all ksql nodes receive the commands will be the same. This will guarantee that they all will be in the same state.
Let's consider the example you mentioned where we have two CTAS statements, S1 and S2, from two different nodes. Assuming the statements are correct both of them will write their statement into the command topic. There will be two cases, either S1 will be written first and then S2 or the vice versa. In either case when all the nodes read the statements from the command topic, all of them will see the same order. Let's say the order is S1 is written first and S2 second. All nodes will first read and execute S1. They then read and try to execute S2 and this execution will fail and user will know that the second statement had conflicts and did not execute. Note that we do not loose any information on the statements and all the decisions on how to manage queries are taken in KSQL without loosing any information.

**Comment by dguy** [comment]
I'm not sure where we are at with this, but i'd like to get some closure. It seems to me that @bluemonk3y and @apurvam are in favour of simplifying, i.e., this PR, and delaying the decision to add more complicated support after discussion, feedback, etc. Of course i am in favour of this, too. What is the verdict?

**Comment by apurvam** [comment]
Thanks for the clarification @hjafarpour . If all nodes only assign query ids execute statements after reading from the command topic --even if they just wrote to it-- then the existing scheme is correct.

**Comment by dguy** [comment]
I'm trying to think what to do with this. At the moment, in either case, it is flawed. 
If we leave it as is, i.e., without a compacted topic, then we have a couple of issues. Once the topic retention has expired we lose information, and any restarted or new nodes that come online will have an incomplete picture. Also, we execute every command even if it has been dropped (which is horrible waste of resources etc). We can work around this in `getAllPriorCommandRecords`, i.e., by compacting ourselves, but then that would result in `queryIds` diverging on different engines.
In the case of this PR, compaction is an issue, as @hjafarpour stated above, if we get 2 `create blah` messages on the command topic then eventually the second one will overwrite the first and we will end up in a different state on new or restarting engines. 
It isn't exactly clear to me how to fix it at the moment...

**Comment by guozhangwang** [comment]
This is a very interesting discussion! Just chime in with my two cents:

1. I think in the long run separating `Query Management` (usually the responsibility of KSQL users) and `Topic Management` (usually the responsibility of Kafka Ops) is a good idea. Because these two groups of people have different goals in mind: for the latter people care about capacity planning, cluster health, req handling performance, while for the former people care about (re)-deploying their query with changes, state management (including offset management, etc). Coupling topic cleanup upon query termination may be restrictive for the former group of people.

2. There are indeed some user scenarios where people would prefer to not cleanup the topic even after terminating the query, for example a) update the query (think: change the predicate threshold) by stop-codechange-restart, in which people would want to write to the tail of the previous same output topic, b) multiple queries sharing the same output topic, such cases may happen for logging purposes (of course there is a question of how to align multiple' stream job's timestamps). So I think it is better not enforcing 1:1 mapping from query to topic.

3. Admittedly both of these argument are quite high-level and probably far-fetch that needs more discussions on how to efficiently support such features, and we do not have the `IF NOT EXIST` syntax in KSQL today. However, with the current approach of `sending tombstones when queries are terminated` looks like a drastic closing-door decision; on the other hand, maybe we can think of a different way, for example relying on tooling (when terminating a query, popping up a user-facing question on whether she want to delete the topic as well? and if yes run some tools to delete the topic) to reduce footprints on the Kafka cluster.

**Comment by dguy** [comment]
@guozhangwang there is a mixture of short term and long term goals. Right now it isn't correct and the correct behaviour for how it all works at the moment is to drop the table/stream when the query is terminated as you can't re-use it once it has been terminated. So the idea is to make it stable and sensible in the short-term, but that doesn't preclude making it more sophisticated in the future.

**Comment by dguy** [comment]
Note: this isn't ready to review yet. I'm updating it and will let you know when it is.

**Comment by apurvam** [comment]
This patch should target the`master` branch.

**Pull request closed without merging**
