### PR TITLE
Add external dependency on Avro Random Generator and remove its source code

### PR DESCRIPTION
**Pull request by C0urante**
The Avro Random Generator project has been officially migrated to Confluent (https://github.com/confluentinc/avro-random-generator) and released as an artifact on Maven central. This PR removes its source code from the KSQL project and adds a dependency on the published Maven artifact.

### CODE REVIEW

**Comment by rodesai** [comment]
What's the process now for changing the generator? How do new artifacts get picked up by the ksql build?

**Comment by C0urante** [comment]
@rodesai I can think of two options:

1) Declare a snapshot dependency on the generator and adjust the generator's build pipeline to automatically publish snapshots to our internal Nexus
2) Publish a new public release of the generator every time a new change is merged to it, and bump the version used by KSQL accordingly

I'd recommend option 2, as the development rate on the generator seems low enough that publishing a new release for every change is actually pretty feasible.

@hjafarpour Ran though the quickstart; everything worked as expected.

**Comment by hjafarpour** [comment]
I also like option 2. No dealing with snapshot dependencies! :)

**Comment by C0urante** [comment]
@rodesai does that work for you? Just waiting for your approval before merging.

**Comment by C0urante** [comment]
Thanks guys!

**Pull request merged**
