### PR TITLE
Fix issues with string concat using '+' operator.

### LINKED ISSUE #1396: Unsupported arithmetic types. STRING STRING
Version : 5.0.0-beta30

This statement used to work, but now fails. Presumably because the `+` is not being treated as a string concatenation operator? 

```
ksql> CREATE STREAM KSQL_NOTIFY WITH (VALUE_FORMAT='JSON') AS \
> SELECT TIMESTAMPTOSTRING(DATE, 'yyyy-MM-dd HH:mm:ss') + ' 👽 ' + MESSAGE + ' 👽' AS TEXT, \
>        'general' AS CHANNEL \
> FROM SYSLOG_INVALID_USERS;
Unsupported arithmetic types. STRING STRING
ksql>
```

### PR DESCRIPTION
**Pull request by big-andy-coates**
Fix for regression #1396, with added test cases.

Fixes #1396 

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by big-andy-coates** [comment]
> Was the regression introduced during the recent UDF changes?

Yep, looks like it.

**Comment by dguy** [comment]
should this go to 5.0.x?

**Comment by big-andy-coates** [comment]
If I merge, can you bring this across to 5.0 as / when you move the UDF stuff into 5.0?

**Comment by big-andy-coates** [comment]
Closing, as now replaced by linked 5.0.x branch PR.

**Pull request closed without merging**
