### PR TITLE
chore: enable tests 

### PR DESCRIPTION
**Pull request by wcarlson5**
there were a few tests that were broken that are fixed now that we have blocking add and remove topologies merged

### Testing done 
_Describe the testing strategy. Unit and integration tests are expected for any behavior changes._

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Review by lct45 — APPROVED** [review]
lgtm when build passes

**Comment by ableegoldman** [comment]
Looks like we still have a few failing tests:
```
io.confluent.ksql.integration.EndToEndIntegrationTest.shouldSupportDroppingAndRecreatingJoinQuery[true]
io.confluent.ksql.integration.EndToEndIntegrationTest.shouldRegisterCorrectPrimitiveSchemaForCreateAsStatements[true]
io.confluent.ksql.integration.EndToEndIntegrationTest.shouldCleanUpAvroSchemaOnDropSource[true]
```

@wcarlson5 did the build run since merging the changes to use blocking add/remove or could this be stale?

**Comment by wcarlson5** [comment]
@ableegoldman I did run it. Its passing locally though every time, I am looking into it though. I am not sure why Jenkins and local would be different.

**Comment by ableegoldman** [comment]
I replayed the tests, maybe it just needs to be re-run since merging the PR?

**Comment by ableegoldman** [comment]
I do see some seemingly weird things in the logs btw, for example in `shouldCleanUpAvroSchemaOnDropSource` we only ever see one copy of a KafkaStreams app being created before hitting this error (eg the line `Kafka Streams version:` is only printed once, we see it come up (without being started) then shut down to NOT_RUNNING -- then some time after that, all of a sudden we hit this error. Could we be reusing the validation runtime after it was shut down? regardless of whether this particular test is failing, that seems very odd to me

**Comment by wcarlson5** [comment]
That is really odd. The Validation runtimes should not be the issue since the PR that has them use the topologies is not merged yet. Also they are never started so they shouldn't be able to make a stateDir

Maybe Jenkins is running these three tests at once? 

Are those the full logs because that doesn't quite seem like what I would expect at all?

**Comment by ableegoldman** [comment]
Idk,  but I see that the same tests failed again.

@wcarlson5 I think it might make sense for me to hand off the one large remaining ksql ticket on my plate ([KCI-859](https://confluentinc.atlassian.net/browse/KCI-859)) to you, and then tackle any new or existing debugging/investigational work as my top priority,  alongside reviewing and the planning work for MD -- let's discuss tomorrow

**Pull request merged**
