### PR TITLE
fix: complete transition to 7.5.x series

### PR DESCRIPTION
**Pull request by vvcephei**
### Description 
pinned-dependencies tooling is only partially completed, so CP branch cuts require some manual work. This commit bumps our SR dependency to the 7.5 series, pins the parent pom in the 7.5 series, and fixes a failing test related to the updated SR dependency.

### Testing done 
running the CI job is sufficient

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Review by milosimpson — APPROVED** [review]
🚢

**Review by Gerrrr — COMMENTED** [review]
Failed test:

```
io.confluent.ksql.services.SandboxedSchemaRegistryClientTest$UnsupportedMethods.shouldThrowOnUnsupportedOperation
```

```
Error Message
Expected exception: java.lang.UnsupportedOperationException
```

The test failure seems relevant.

**Comment by vvcephei** [comment]
Thanks for pointing that out, @Gerrrr . The failing test was telling us that a new method has been added to the SRClient that wasn't explicitly handled in the Sandboxed wrapper. I added it to the wrapper as a disallowed method (it just throws an exception). If we need to use it at any point, we can change the sandbox then.

**Review by Gerrrr — APPROVED** [review]
LGTM assuming the tests pass.

**Pull request merged**
