### PR TITLE
docs: intent for klip-62: ksqlDB Ruby client

### PR DESCRIPTION
**Pull request by LapoElisacci**
docs: intent for klip-62: ksqlDB Ruby client

The development has already started, you can find the progress [here](https://github.com/LapoElisacci/ksql/issues/9).

### CODE REVIEW

**Comment by LapoElisacci** [comment]
[clabot:check]

**Comment by cprasad1** [comment]
Thanks @LapoElisacci ! Can you submit a Proposal Intent (as described [here[(https://github.com/confluentinc/ksql/blob/master/design-proposals/README.md#proposal-intent) first before we dive into the discussion about the design? You can expect it to be merged quickly

**Comment by LapoElisacci** [comment]
Hey @cprasad1 I've renamed the PR as described, am I missing something else?
Cheers

**Comment by cprasad1** [comment]
The intent for KLIP PR does not include the KLIP itself, so we can remove the actual KLIP from this PR. You can open a new PR after the intent has been merged and we can discuss the design there. @LapoElisacci

**Comment by LapoElisacci** [comment]
Alright, I've removed the actual KLIP from this PR.
What's the next step?

Thanks

**Comment by cprasad1** [comment]
thanks @LapoElisacci ! I will merge this once this gets a green build. ksqlDB master is broken right now, so we have to wait for it to get fixed before we merge this. You can check the status of master here https://github.com/confluentinc/ksql/commits/master. Meanwhile, can You open a second PR with the actual KLIP , and we can continue the conversation there.

**Review by cprasad1 — APPROVED** [review]

**Comment by LapoElisacci** [comment]
Thanks @cprasad1, I've created the new PR and changed the discussion link.
Here it is https://github.com/confluentinc/ksql/pull/8865

**Comment by cprasad1** [comment]
merging since this is only a docs update. Thanks @LapoElisacci !

**Pull request merged**
