### PR TITLE
chore: ensure ImmutabilityTest is run by build

### PR DESCRIPTION
**Pull request by big-andy-coates**
### Description 

Running the  `ImmutabilityTest` locally fails due to some issues with new rest model classes.  This is likely caused by all instances of the `ImmutabilityTest` being in the same package, so results from one are potentially overwriting results from another when being processed by the build servers.

This change moves each test into a unique package and fixes up some known issues in the code.

Wondering why there are multiple instances of this test class? Each _leaf_ module needs a copy of the test to ensure all classes are tested.

### Testing done 

Ran locally.  This build will hopefully fail, highlighting the current immutability issues in the code.

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by big-andy-coates** [comment]
Turns out the issue is not related to tests being in the same package, though that does seem to cause the build server to lose some of the results.  

The issue is that the `install` maven target does things differently to `test`. 

If you run `mvn test` then each `ImmutabilityTest` will find any immutable classes in the current module and any other modules it depends on.  

If you run `mvn install` then each `ImmutabilityTest` will only find immutable classes in the current module.

I'd previously only installed these tests in the _leaf_ modules, e.g. modules that nothing else depended on: `ksql-cli`, `ksql-functional-test` and `ksql-rest-app`.  This was done on the assumption that Maven worked.

**I HATE MAVEN**

I've no idea why this is and nothing obvious pops up on Google when I search for this.  Given Maven is a pile of junk, I don't think there's much ROI in trying to work out what the difference is.  Hence, I've just added a copy of the test to each module.  This fixes the issue, even if it ain't pretty.

If there is anyone out there with Maven knowledge that can work out what's going on, then please do!

**Comment by big-andy-coates** [comment]
Build is now correctly failing due to types tagged as immutable that, potentially, aren't:

- io.confluent.ksql.rest.entity.ClusterStatusResponse
- io.confluent.ksql.rest.entity.LagReportingMessage

@vpapavas  can you take a look at these please?

FYI, heavily nested field types, e.g. 

```java
// from ClusterStatusResponse
private final Map<HostInfoEntity, Map<QueryStateStoreId, Map<Integer, LagInfoEntity>>> lags;
```

Are generally best avoided.  They're hard to get your head around and generally lead to some very hard to understand code, as the key and value type don't necessarily impart information as to _what_ they are, e.g. it's not clear what the `Integer` is in the most nested map.  Having custom types means you can add much more descriptive names, which makes code more understandable, e.g. `getPartitionLag` imparts more info than just `get`.

I'd highly recommend breaking the different layers out into different immutable types, e.g. 
* `StateStoreLags` can track `LagInfoEntity` by partition, (assuming that's what the int is).
* `HostStoreLags` can track all the `StateStoreLags` for a host

This then means `ClusterStatusResponse` just has a map of `HostInfoEntity` -> `HostStoreLags`.

**Comment by AlanConfluent** [comment]
I'll fix the immutability tests and try to introduce some additional objects.

**Comment by AlanConfluent** [comment]
https://github.com/confluentinc/ksql/pull/4417

**Pull request merged**
