### PR TITLE
test: fix QTT tests after upstream change (#7306)

### PR DESCRIPTION
**Pull request by ableegoldman**
Cherrypick of fix in 6.1.x: [#7306](https://github.com/confluentinc/ksql/pull/7306) as these three tests have been failing on 6.0.x (presumably since the emit-on-change logic was originally reverted in Streams, so almost two months)

Cf. https://issues.apache.org/jira/browse/KAFKA-12508

### CODE REVIEW

**Review by agavra — APPROVED** [review]
lgtm if tests pass 🟢

**Comment by ableegoldman** [comment]
dammit Jenkins 😠  Not this again (thanks for the heads up)

**Comment by ableegoldman** [comment]
Is it possible the tests don't run on PRs that just contain a cherrypick of a previously tested PR/commit? I think I vaguely recall this happening before in a similar situation. Or does Jenkins just hate me 😞

**Review by mjsax — APPROVED** [review]

**Comment by mjsax** [comment]
Don't forget to `pint merge` :)

**Comment by ableegoldman** [comment]
Merged with pint

**Pull request merged**
