### PR TITLE
disable spotbugs false-positive with Java 11

### PR DESCRIPTION
**Pull request by xvrl**
This is a workaround for the following issue using spotbugs and Java 11
https://github.com/spotbugs/spotbugs/issues/756

### CODE REVIEW

**Comment by xvrl** [comment]
We never fail the build in the common pom, only warm, but ksql overrides it.

**Comment by ijuma** [comment]
Thanks for the explanation. I think the KSQL team likes warning free builds, so they may prefer if this was disabled altogether. Let's see what they think. cc @big-andy-coates

**Comment by hjafarpour** [comment]
I also defer the judgment on this to @big-andy-coates !

**Comment by big-andy-coates** [comment]
@xvrl are we building KSQL on Java 11, or intending too any time soon?

It feels very wrong to not fail the build if spot bugs finds a potential issue. If we turn this off, then I guarantee we'll have potential bugs in the build within 4 weeks. Because people don't notice if there are warnings.

So... if we need Java 11 support before this is fixed upstream, then we need to find a way to selectively disable this spotbug check, rather than the whole of spotbugs.

**Comment by xvrl** [comment]
@big-andy-coates Yes, we plan to start building against Java 11, so that we can be ready to support it. We already build PRs against Java 10 to ensure PRs don't introduce incompatibilities with newer Java releases. Since 10 was EOLed, it makes sense to move on to 11. For KSQL, this is the last remaining issue to pass tests with Java 11.

I am not suggesting to turn off spotbugs completely, this is only activated for JDK11 builds. The master branch build still runs against JDK8 with spotbugs turned on, and would catch any regressions.

It's unclear if the spotbugs issue will be resolved anytime soon, since it's an artifact of the bytecode generated by the JDK, which may require waiting for a future JDK release to be resolved.

We can look into turning off individual warnings, but that seems very tedious. FWIW, Kafka decided to turn off spotbugs completely when building with Java 11.

**Comment by ijuma** [comment]
I think we are going to disable that warning in AK. It's unlikely that it's going to work in Java 11 since they said that javac is within the spec.

**Comment by xvrl** [comment]
@big-andy-coates I've updated the PR to disable the warning in question rather than turning off spotbugs.

**Comment by xvrl** [comment]
@ewencp there are other fixes on master that address some Java 8 vs 9 issues so I'm going to merge this to master and we can backport as needed if we want to get this into 5.1

**Pull request merged**
