### PR TITLE
[hotfix] Disable SslClientAuthFunctionalTest to unblock build 7.5.x

### PR DESCRIPTION
**Pull request by jiaxuqin521**
### Description 
Disable SslClientAuthFunctionalTest to unblock build 7.5.x
Discussion link: https://confluent.slack.com/archives/C9Z794XSL/p1699981849954699

### Testing done 
_Describe the testing strategy. Unit and integration tests are expected for any behavior changes._

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")
- [ ] Do these changes have compatibility implications for rollback? If so, ensure that the ksql [command version](https://github.com/confluentinc/ksql/blob/master/ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/Command.java#L41) is bumped.

### CODE REVIEW

**Review by cprasad1 — APPROVED** [review]
Thanks @jiaxuqin521 ! Can we use the @Disabled annotation instead of commenting out the tests? No strong opinion given the desire to unblock

**Comment by mjsax** [comment]
Yes, using `@Ignore` annotation sound more appropriate.

**Comment by cprasad1** [comment]
Ah yes @Ignore if it's junit 4

**Comment by jiaxuqin521** [comment]
I got error when I try to push new commit to this PR.
So I create a new one by using ignore: https://github.com/confluentinc/ksql/pull/10117 
@cprasad1

**Pull request closed without merging**
